/* REQ-037: deterministic review rules. Integer cents; no provider or server calls. */
window.PrototypeRules = (() => {
  const h=React.createElement;
  function ratio(value) {
    const s=String(value);if(!/^-?\d+(\.\d+)?$/.test(s))throw Error('金额或比例格式不正确');
    const negative=s.startsWith('-'),parts=s.replace('-','').split('.'),digits=parts[1]||'';
    return [BigInt(parts[0]+digits)*(negative?-1n:1n),10n**BigInt(digits.length)];
  }
  const rounded=(n,d)=>(n<0n?-1n:1n)*((2n*(n<0n?-n:n)+d)/(2n*d));
  function cents(value){const [n,d]=ratio(value),v=Number(rounded(n*100n,d));if(!Number.isSafeInteger(v))throw Error('金额超出范围');return v;}
  function share(fee,rule){const f=cents(fee);if(f<0||!rule||!['按比例','按金额'].includes(rule.mode))throw Error('费用或分配规则缺失');const [n,d]=ratio(rule.value);if(n<0n||rule.mode==='按比例'&&n>100n*d)throw Error('分配规则超出范围');return rule.mode==='按比例'?Number(rounded(BigInt(f)*n,100n*d)):cents(rule.value);}
  function allocation(fee,source,channel){const feeCents=cents(fee),sourceCents=share(fee,source),channelCents=share(fee,channel),platformCents=feeCents-sourceCents-channelCents;if(platformCents<0)throw Error('资源方与渠道方分配之和不能超过获客费');return {feeCents,sourceCents,channelCents,platformCents};}
  function addDays(date,n){const d=new Date(date+'T00:00:00Z');if(!Number.isFinite(+d)||d.toISOString().slice(0,10)!==date)throw Error('日期无效');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10);}
  const deadline=(issue,cycle)=>addDays(issue,cycle==='周结'?3:5);
  const scheduled=(date,cycle)=>cycle==='周结'?new Date(date+'T00:00:00Z').getUTCDay()===1:date.slice(8)==='01';
  function collectUnbilled(items,cycle,issue){if(!['周结','月结'].includes(cycle)||!scheduled(issue,cycle))throw Error('尚未到新周期出账日');return items.filter(t=>!t.billId&&!t.cancelled&&t.status!=='已撤销'&&t.date.slice(0,10)<issue);}
  function reversalError(r,b){if(!r||r.status!=='已核销')return '该核销已经撤销或不存在';if(r.settled||b?.status==='已结清')return '账单已完成结算，不能撤销核销';if(b&&(['支付中','结果未知'].includes(b.payment)||b.status==='付款待审核'||b.receipts?.some(x=>x.status==='待审核')||b.attempts?.some(x=>['待支付','结果待核实'].includes(x.status))))return '存在未决支付或待审核收款，请先核实，不能撤销';return '';}
  function Login({title,org,onLogin}){
    const [phone,setPhone]=React.useState(''),[code,setCode]=React.useState(''),[sent,setSent]=React.useState(0),[error,setError]=React.useState('');
    const valid=()=>/^1380000000[1-4]$/.test(phone);
    return h('div',{className:'login'},h('h2',null,title+'登录'),h('p',null,org+' · 手机号与验证码'),h(arco.Alert,{content:'本地登录演示，不发送短信。预开通演示手机号13800000001～04，获取后使用验证码123456；请勿输入真实信息。'}),h('label',null,'手机号',h(arco.Input,{value:phone,onChange:v=>{setPhone(v);setSent(0)},placeholder:'预开通的演示手机号'})),h(arco.Button,{onClick:()=>{if(!valid()){setError('手机号未开通或格式错误，请联系管理员');return}setSent(Date.now());setError('演示验证码：123456（5分钟内有效，不发送短信）')}},'获取验证码（演示）'),h('label',null,'验证码',h(arco.Input,{value:code,onChange:setCode,placeholder:'6位演示验证码'})),error&&h(arco.Alert,{content:error}),h(arco.Button,{type:'primary',long:true,onClick:()=>{if(!valid()||code!=='123456'||!sent||Date.now()-sent>300000){setError('请先获取有效验证码并正确填写');return}setSent(0);onLogin();}},'进入演示后台'));
  }
  function Cycle({clinic,pages,save}){
    const W=window.PrototypeWorkflows,[cycle,setCycle]=React.useState('月结'),[reason,setReason]=React.useState(''),[date,setDate]=React.useState('2026-10-01'),[error,setError]=React.useState('');
    const current=clinic.contractVersions?.find(c=>['已生效','即将到期'].includes(c.status)&&c.start<='2026-09-07'&&c.end>='2026-09-07'),pending=clinic.cycleRequest,role=window.PROTOTYPE.role;
    const commit=fn=>{try{const p=JSON.parse(JSON.stringify(pages)),c=p.find(p=>p.id==='clinics').rows.find(c=>c.id===clinic.id);fn(c,p);save(p);setError('');}catch(e){setError(e.message)}};
    const fixture=()=>commit(c=>{if(c.unbilledDemo)return;c.unbilledDemo=[{id:'CYCLE-OLD-'+c.id,date:'2026-07-12',amount:60,status:'未出账'},{id:'CYCLE-NEW-'+c.id,date:'2026-09-06',amount:60,status:'未出账'},{id:'CYCLE-ISSUED-'+c.id,date:'2026-08-20',amount:60,status:'已出账',billId:'历史已出账示例'}];});
    if(!current)return h(arco.Alert,{content:'有效合同生效后可申请变更结算周期。'});
    const request=()=>commit(c=>{if(c.cycleRequest?.status==='待审核')throw Error('已有待审核变更');if(cycle===current.cycle||!reason.trim())throw Error('请选择不同周期并填写变更原因');c.cycleRequest={id:'CYCLE-'+Date.now(),contract:current.id,version:current.version,oldCycle:current.cycle,newCycle:cycle,reason:reason.trim(),status:'待审核'};c.history.push({id:'CYCLE-REQ-'+Date.now(),name:'提交账期变更：'+reason,status:'待审核',date:'2026-09-07'});});
    const review=pass=>commit(c=>{if(role!=='platform'||c.cycleRequest?.status!=='待审核')throw Error('仅平台审核待处理变更');if(!reason.trim())throw Error('请填写审核意见');const request=c.cycleRequest,ct=c.contractVersions.find(v=>v.id===request.contract);if(!ct||ct.version!==request.version||ct.cycle!==request.oldCycle)throw Error('合同版本已变化，请重新申请');request.status=pass?'审核通过':'审核不通过';request.review=reason.trim();if(pass){ct.cycle=request.newCycle;ct.version++;c.cycle=ct.cycle;}c.history.push({id:'CYCLE-REVIEW-'+Date.now(),name:(pass?'通过':'退回')+'账期变更：'+reason,date:'2026-09-07',status:request.status});});
    return h('section',{className:'panel'},h('h3',null,'结算周期变更'),h(arco.Alert,{content:'当前'+current.cycle+'。渠道申请、平台审核后立即生效；全部未出账历史交易按新账期出账，已出账单不重排。不在修改合同当天立即出单。'}),error&&h(arco.Alert,{type:'error',content:error}),W.field('新结算周期',h(arco.Select,{value:cycle,onChange:setCycle,options:['周结','月结']})),W.field(role==='platform'?'变更审核意见':'账期变更原因',h(arco.Input.TextArea,{value:reason,onChange:setReason})),role==='channel'&&h(arco.Button,{onClick:request,disabled:pending?.status==='待审核'},'提交账期变更'),role==='platform'&&!pending&&h(arco.Button,{onClick:request},'加载渠道申请示例（仅评审）'),pending&&h(React.Fragment,null,h('p',null,pending.oldCycle+' → '+pending.newCycle+' · '+pending.status+' · '+pending.reason),role==='platform'&&pending.status==='待审核'&&h('div',null,h(arco.Button,{type:'primary',onClick:()=>review(true)},'通过账期变更'),h(arco.Button,{onClick:()=>review(false)},'退回账期变更'))),
    h('h4',null,'账期归集演示'),h(arco.Alert,{content:'以下为独立虚构交易，不是实际定时任务。只归集出账日前、尚未入单的有效交易。'}),!clinic.unbilledDemo?h(arco.Button,{onClick:fixture},'加载未出账交易示例'):h(React.Fragment,null,h(W.RecordList,{items:clinic.unbilledDemo,states:['未出账','已出账'],columns:[['id','交易编号'],['date','核销日期'],['amount','获客费'],['billId','账单编号'],['status','状态']]}),role==='platform'&&h(React.Fragment,null,W.field('模拟出账日期',h(arco.DatePicker,{value:date,onChange:setDate,allowClear:false})),h(arco.Button,{onClick:()=>commit((c,p)=>{const ct=c.contractVersions.find(v=>v.id===current.id),items=collectUnbilled(c.unbilledDemo,ct.cycle,date);if(!items.length)throw Error('无可出账交易，不重复生成');const id='CYCLE-BILL-'+Date.now(),amount=items.reduce((n,t)=>n+cents(t.amount),0)/100;p.find(p=>p.id==='bills').rows.push({id,name:c.name,period:'截至'+addDays(date,-1)+'的历史未出账交易',issueDate:date,deadline:deadline(date,ct.cycle),cycle:ct.cycle,contractVersion:ct.version,amount,confirmed:0,status:'待付款',flowVersion:29,revision:1,receipts:[],attempts:[],history:[{id:id+'-LOG',name:'按新账期归集历史未出账交易',date,status:'已出账'}],items:items.map(t=>({id:t.id,appointment:t.id,redemption:t.id,date:t.date,quantity:1,feeCents:cents(t.amount),amountCents:cents(t.amount),status:'有效核销',productName:'舒适洁牙权益',clinic:c.name}))});items.forEach(t=>{t.billId=id;t.status='已出账'});c.history.push({id:id+'-LOG',name:'模拟按'+ct.cycle+'归集 '+items.length+'笔；已出账不重排',date,status:'已出账'});})},'模拟按当前账期出账'))));
  }
  return {Cycle,cents,share,allocation,addDays,deadline,scheduled,collectUnbilled,reversalError,Login};
})();
