/* 0.18业务原型：各角色只读取自己的配置与本地数据，无网络收款或跨角色同步。 */
window.PrototypeWorkflows = (() => {
  const h = React.createElement, {useState} = React;
  const {Button, Tabs, Table, Tag, Alert, Input, InputNumber, Select, DatePicker, Checkbox, Modal, Drawer, Descriptions, Upload, Image, Empty, Message} = arco;
  const TODAY = '2026-09-07', clone = v => JSON.parse(JSON.stringify(v));
  const uid = prefix => prefix + '-' + Date.now() + '-' + Math.random().toString(36).slice(2,7);
  const rows = (pages,id) => pages.find(p=>p.id===id)?.rows || [];
  const active = c => ['已生效','即将到期'].includes(c.status) && c.start<=TODAY && c.end>=TODAY;
  const nextDay = value => {const d=new Date(value+'T00:00:00Z');d.setUTCDate(d.getUTCDate()+1);return d.toISOString().slice(0,10)};
  const money = n => Number(n||0).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});
  const notice = (text,type='info') => h(Alert,{type,content:text,style:{marginBottom:16}});
  const button = (text,onClick,props={}) => h(Button,{onClick,...props},text);
  const section = (title,...children) => h('section',{className:'panel flow-section'},h('h2',null,title),...children);
  const details = items => h(Descriptions,{column:2,border:true,data:items.map(([label,value])=>({label,value:value??'—'}))});
  const field = (label,input) => h('div',{className:'flow-field'},h('div',{className:'flow-label'},label),React.cloneElement(input,{'aria-label':label}));
  const tag = s => h(Tag,{color:/待|即将/.test(s)?'orange':/拒绝|退回|逾期|不通过/.test(s)?'red':/已生效|通过|已结清|已上线|成功/.test(s)?'green':'arcoblue'},s);
  function sample(name,kind='合同附件') {
    name=String(name).replace(/[<>&]/g,'');kind=String(kind).replace(/[<>&]/g,'');
    const svg='<svg xmlns="http://www.w3.org/2000/svg" width="760" height="480"><rect width="760" height="480" fill="#f2f6fc"/><rect x="24" y="24" width="712" height="432" rx="4" fill="white" stroke="#c9d8ee"/><text x="55" y="100" font-size="26" fill="#165dff">齿慧通 · '+kind+'</text><text x="55" y="168" font-size="22">'+name+'</text><text x="55" y="228" font-size="18" fill="#4e5969">虚构评审资料 · 不含真实个人或机构信息</text><path d="M55 275H700M55 310H640M55 345H690" stroke="#e5e6eb"/><text x="55" y="405" font-size="20" fill="#f53f3f">仅供原型预览 · 非有效证照或签署文件</text></svg>';
    return {id:uid('FILE'),name:name+'.svg',kind,type:'image/svg+xml',url:'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svg),sample:true};
  }
  const fileOK = f => !!f.url && (f.sample ? f.url.startsWith('data:image/svg+xml;') : /^data:(image\/(png|jpeg)|application\/pdf);base64,/.test(f.url));
  function Files({files=[],onChange,defaultKind='合同附件'}) {
    const [error,setError]=useState(''),[preview,setPreview]=useState(null),[reading,setReading]=useState(false);
    const load = file => {
      if(!/\.(png|jpe?g|pdf)$/i.test(file.name)||!['image/png','image/jpeg','application/pdf'].includes(file.type)||file.size>512*1024){setError('仅支持PNG/JPG/PDF，单文件不超过512KB；请使用无敏感信息的演示文件。');return false}
      if(files.length>=10){setError('演示附件最多10份，请移除无用文件后重试。');return false}
      setReading(true);const reader=new FileReader();reader.onload=async()=>{try{if(file.type.startsWith('image/')){const img=new window.Image();img.src=reader.result;await img.decode()}else if(!atob(String(reader.result).split(',')[1]).startsWith('%PDF-'))throw Error('invalid PDF');onChange([...files,{id:uid('FILE'),name:file.name,type:file.type,kind:defaultKind,url:reader.result}]);setError('')}catch{setError('文件内容无法读取，请选择有效图片或PDF。')}finally{setReading(false)}};reader.onerror=()=>{setReading(false);setError('文件读取失败，请重新选择。')};reader.readAsDataURL(file);return false;
    };
    return h('div',{className:'flow-files'},h('p',{className:'muted'},'全部材料 '+files.length+' 份 · 图片点击放大，PDF点击预览。仅本地保存，请勿上传真实资料。'),
      error&&notice(error,'error'),
      h('div',{className:'file-grid'},...files.map(f=>h('div',{key:f.id,className:'file-card'},fileOK(f)?(f.type.startsWith('image/')?h(Image,{src:f.url,width:150,height:96,alt:f.name,fit:'contain',preview:true}):button('预览PDF',()=>setPreview(f))):notice('缺失或无法读取，请重新上传','error'),h('strong',null,f.name),h('span',{className:'muted'},f.kind||'附件'),fileOK(f)&&h('a',{href:f.url,download:f.name},'下载附件'),onChange&&h(Select,{value:f.kind,options:['营业执照','医疗机构执业许可证','门诊照片','签署合同','合同附件','付款凭证','其他材料'],onChange:kind=>onChange(files.map(x=>x.id===f.id?{...x,kind}:x)),size:'small','aria-label':'附件类别 '+f.name}),onChange&&button('移除',()=>onChange(files.filter(x=>x.id!==f.id)),{size:'small',type:'text',status:'danger'})))),
      !files.length&&h(Empty,{description:'尚未提交附件'}),onChange&&h('div',{className:'flow-actions'},h(Upload,{autoUpload:false,showUploadList:false,accept:'.png,.jpg,.jpeg,.pdf',beforeUpload:load,disabled:reading},button(reading?'正在读取…':'上传照片或附件',null,{disabled:reading})),button('使用演示附件',()=>onChange([...files,sample('补充资料-'+(files.length+1),defaultKind)]),{disabled:reading||files.length>=10})),
      preview&&h(Modal,{visible:true,title:preview.name,footer:null,onCancel:()=>setPreview(null),style:{width:800,maxWidth:'95vw'}},h('iframe',{src:preview.url,title:preview.name,style:{width:'100%',height:'65vh',border:0}})));
  }
  function RecordList({items,columns,states=[],onView,actions,search=true,exportName,onExport,exportLabel='下载Excel',tableWidth=650,actionWidth,initialStatus='全部'}) {
    const [status,setStatus]=useState(initialStatus),[query,setQuery]=useState(''),[page,setPage]=useState(1);
    const matched=items.filter(r=>Object.values(r).some(v=>typeof v!=='object'&&String(v).includes(query))),shown=matched.filter(r=>status==='全部'||r.status===status);
    const tabs=['全部',...new Set([...states,...items.map(r=>r.status)].filter(Boolean))];
    const exportRows=()=>{const esc=v=>'"'+String(v??'').replace(/^[=+@-]/,"'").replace(/"/g,'""')+'"';const csv='\ufeff'+[columns.map(c=>esc(c[1])).join(','),...shown.map(r=>columns.map(c=>esc(r[c[0]])).join(','))].join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=exportName+'-演示.csv';a.click();URL.revokeObjectURL(url)};
    return h(Tabs,{className:'status-tabs',activeTab:status,onChange:v=>{setStatus(v);setPage(1)},overflow:'scroll',destroyOnHide:true,animation:false},...tabs.map(t=>h(Tabs.TabPane,{key:t,title:t+'（'+matched.filter(r=>t==='全部'||r.status===t).length+'）'},status===t&&h(React.Fragment,null,
      h('div',{className:'toolbar'},onExport&&button(exportLabel,()=>Modal.confirm({title:'下载当前范围Excel？',content:'包含当前筛选后的全部分页，不包含其他机构。',onOk:()=>onExport(shown,'状态：'+status+'；关键词：'+(query||'无'))})),search&&h(Input.Search,{value:query,onChange:v=>{setQuery(v);setPage(1)},allowClear:true,placeholder:'搜索编号、名称或关键字',style:{width:260}}),exportName&&button('导出数据',()=>Modal.confirm({title:'导出当前范围？',content:'仅导出当前角色和状态筛选后的演示记录。',onOk:exportRows}))),
      h(Table,{rowKey:'id',data:shown,scroll:{x:tableWidth},pagination:{current:Math.min(page,Math.max(1,Math.ceil(shown.length/8))),pageSize:8,onChange:setPage,showTotal:true},noDataElement:h(Empty,{description:'暂无符合条件的记录'}),columns:[...columns.map(([key,title])=>({dataIndex:key,title,fixed:key==='id'&&tableWidth>1000?'left':undefined,width:key==='id'&&tableWidth>1000?190:undefined,align:['amount','fee','quantity'].includes(key)?'right':'left',render:(v,r)=>key==='status'?tag(v):key==='value'&&r.mode?String(v)+(r.mode==='按比例'?'%':' 元/次'):['amount','fee'].includes(key)?money(v):v??'—'})),...((onView||actions)?[{title:'操作',width:actionWidth||(tableWidth>1000?140:200),fixed:tableWidth>1000?'right':undefined,render:(_,r)=>h('div',{className:'flow-actions'},onView&&button('详情',()=>onView(r),{type:'text'}),actions&&actions(r))}]:[])]})))));
  }
  const audit = (pages,text,subject) => {const p=pages.find(p=>p.id==='audit');if(p)p.rows.unshift({id:uid('LOG'),name:text,subject,operator:window.PROTOTYPE.user,time:TODAY,status:'已记录'})};
  function cleanText(v) {return typeof v==='string'?v.replace(/信用与账单/g,'账单与收款').replace(/信用与结算/g,'账单与收款').replace(/确认预约不占用信用额度/g,'确认预约不计费').replace(/自身合同及信用条件/g,'三方合同及服务条件').replace(/合同、信用及营业条件/g,'三方合同及营业条件'):v}
  function prepare(config) {
    const visit=o=>{if(!o||typeof o!=='object')return;for(const k of Object.keys(o)){if(typeof o[k]==='string')o[k]=cleanText(o[k]);else visit(o[k])}};visit(config);
    config.version='0.18';
    if(config.role==='channel'){config.schemeCatalog.push({name:'儿童涂氟权益',fee:40,status:'已启用'},{name:'口腔检查权益',fee:20,status:'已启用'});config.pages.find(p=>p.id==='contractSchemes').rows.push({id:'SQ-QM-002',contract:'HT-2026-002',scheme:'儿童涂氟权益',mode:'按金额',value:10,status:'已启用',version:1},{id:'SQ-QM-003',contract:'HT-2026-002',scheme:'口腔检查权益',mode:'按比例',value:20,status:'已启用',version:1});}
    config.cards=config.cards.filter(c=>c.page!=='credit');config.side=config.side.filter(x=>!x.some(v=>/额度|信用/.test(v)));config.scope=cleanText(config.scope).replace('独立合同和额度','独立合同和账单');config.description=config.description.replace('额度申请','三方合同审核').replace('合同、三方合同审核','三方合同');
    config.pages=config.pages.filter(p=>p.id!=='credit');
    for(const p of config.pages){p.columns=p.columns.filter(c=>!['credit','used','availableCredit'].includes(c[0]));for(const a of [p.create,...(p.actions||[])].filter(Boolean))if(a.fields)a.fields=a.fields.filter(f=>f.key!=='credit');}
    if(['resource','channel'].includes(config.role)){
      const p=config.pages.find(p=>p.id==='contracts');p.custom='partner';p.title=config.role==='channel'?'平台合作与推广产品':'合作合同与推广产品';p.description='合同及授权方案同页查看 · 配置由平台负责';p.actions=[];delete p.create;
      config.pages.find(p=>p.id==='contractSchemes').hidden=true;
    }
    if(config.role==='channel'){for(const id of ['clinicContracts','offers'])config.pages.find(p=>p.id===id).hidden=true;config.cards=config.cards.map(c=>c.page==='contracts'?{...c,page:'clinics',title:'门诊合同续签',foot:'进入门诊管理'}:c);}
    const clinics=config.pages.find(p=>p.id==='clinics');if(clinics){clinics.custom='clinics';clinics.description='资料与审核、三方合同及续签、优惠上下线均在门诊内办理';}
    const bills=config.pages.find(p=>p.id==='bills');if(bills){bills.custom='bills';bills.title=config.role==='channel'?'欠款与催收':'账单与收款';bills.description='按合同周结或月结 · 付款凭证审核 / 微信扫码支付';}
    if(config.role==='clinic'){const c=config.pages.find(p=>p.id==='contracts');c.custom='clinicContract';c.title='门诊三方合同';c.description='平台 / 渠道公司 / 门诊 · 由渠道负责签订及续签';config.alert='可提交付款凭证或微信扫码支付；付款待审核不代表结清。逾期不自动下线，由平台人工操作。';}
    if(config.role==='platform'){
      const c=config.pages.find(p=>p.id==='contracts');c.notice='在合作方合同配置多个方案与比例/金额分配；门诊三方合同由渠道提交，请从门诊管理审核。';
      c.create.fields.find(f=>f.key==='type').options=['平台—资源方','平台—渠道公司'];c.create.fields=c.create.fields.filter(f=>!['cycle'].includes(f.key));
      c.rows=c.rows.filter(r=>['平台—资源方','平台—渠道公司'].includes(r.type));
    }
  }
  function makeContract(clinic,index,status='已生效') {return {id:'SF-'+clinic.id+'-V1',number:'SF-2026-'+clinic.id,platform:'齿慧通运营主体（演示）',channel:clinic.channel||'启明渠道（演示）',clinic:clinic.name,start:'2026-01-01',end:'2026-09-30',signed:'2026-01-01',cycle:index%2?'月结':'周结',payer:clinic.name,payee:'齿慧通运营主体（演示）',contact:'门诊财务（演示）',phone:'13800000021',status,version:1,files:[sample(clinic.name+'三方签署页')],history:[]};}
  function migrate(pages) {
    const role=window.PROTOTYPE.role;
    for(const p of pages){
      for(const r of p.rows){if(p.id==='clinics'&&r.status==='逾期临时下线'){r.legacyServiceStatus=r.status;r.status='已暂停';r.serviceReason='历史下线记录保留，需平台核实后人工上线';}if('credit' in r){r.legacyCredit=r.credit;delete r.credit}if(p.id!=='appointments')delete r.used;}
      if(p.id==='clinics')p.rows.forEach((r,i)=>{
        if(r.flowVersion)return;
        r.flowVersion=18;r.subject=r.subject||r.name+'经营主体';r.contact=r.contact||'门诊联系人（演示）';r.phone=r.phone||'13800000021';r.hours=r.hours||'09:00–18:00';r.channel=r.channel||'启明渠道（演示）';r.qualification=['待审核','审核不通过'].includes(r.status)?r.status:'审核通过';r.cycle=r.cycle||'周结';
        r.files=[sample('营业执照','营业执照'),sample('医疗机构执业许可证','医疗机构执业许可证'),sample('门诊环境照片','门诊照片')];
        r.contractVersions=[makeContract(r,i,r.qualification==='待审核'?'待审核':'已生效')];r.schemeStates={};r.history=[];
        for(const old of rows(pages,'offers').filter(o=>o.clinic===r.name||o.name===r.name))r.schemeStates[old.scheme]=old.status;
      });
      if(p.id==='contracts'&&role==='platform')p.rows=p.rows.filter(r=>['平台—资源方','平台—渠道公司'].includes(r.type));
      if(p.id==='contracts'&&role==='clinic'&&!p.rows.some(r=>r.type==='三方合同'))p.rows.push({...makeContract({id:'MZ-001',name:window.PROTOTYPE.org},0),name:'门诊三方服务及结算合同',type:'三方合同'});
      if(p.id==='bills')p.rows.forEach((r,i)=>{if(r.flowVersion)return;r.flowVersion=18;r.receipts=[];r.attempts=[];r.history=[];r.confirmed=r.status==='已结清'?r.amount:0;r.revision=1;r.cycle=r.period?.includes('至')?'周结':'月结';if(role==='platform'&&r.status!=='已结清')r.receipts=[{id:uid('REC'),amount:r.amount,date:TODAY,payer:r.name,status:'待审核',files:[sample('银行转账凭证','付款凭证')]}];if(r.voucher)r.history.push({id:uid('LEGACY'),name:'历史凭证文件名：'+r.voucher+'，未保存内容',date:TODAY,status:'已记录'});});
    }
    return pages;
  }
  function Partner({pages}) {
    const contracts=rows(pages,'contracts').filter(c=>!pages.find(p=>p.id==='contracts').recordType||c.type===pages.find(p=>p.id==='contracts').recordType),current=contracts.find(active)||contracts[0];
    const catalog=window.PROTOTYPE.schemeCatalog||[],[selected,setSelected]=useState(null),[showFiles,setShowFiles]=useState(false);
    const terms=rows(pages,'contractSchemes').filter(t=>t.contract===(selected||current)?.id).map(t=>{const s=catalog.find(s=>s.name===t.scheme),c=selected||current;return {...t,name:t.scheme,fee:s?.fee,conditions:s?.terms||'预约后使用，单次核销1份',split:t.mode+' '+t.value+(t.mode==='按比例'?'%':'元/次'),access:active(c)&&t.status==='已启用'&&s?.status==='已启用'?'可用':'当前不可开展新业务'};});
    const c=selected||current;
    return h(React.Fragment,null,section('合作合同',!contracts.some(active)&&notice('当前没有生效合同；历史内容仍可查看，不能开展新增业务。','warning'),c?details([['合同编号',c.id],['签约主体',c.party],['生效日期',c.start],['到期日期',c.end],['合同状态',tag(c.status)],['业务范围','合同已授权方案']]):h(Empty,{description:'尚无合同'}),c&&button(showFiles?'收起合同附件':'查看合同附件',()=>setShowFiles(!showFiles),{type:'text'}),c&&showFiles&&h(Files,{files:c.files||[sample(c.name||'平台合作合同')]})),section('合同授权推广产品',notice('仅查看本机构合同和分配，新增、修改、启停由平台管理员负责。'),h(RecordList,{items:terms,states:['已启用','已停用'],columns:[['name','推广产品'],['fee','单次获客费（元）'],['conditions','使用条件'],['split','本方分配'],['access','有效性'],['status','授权状态']]})),section('合同与历史版本',h(RecordList,{items:contracts,states:['已生效','已审核待生效','已到期','已终止'],columns:[['id','合同编号'],['name','合同名称'],['start','生效日期'],['end','到期日期'],['status','状态']],onView:setSelected})));
  }
  function ClinicInfoForm({clinic,onSave,onCancel,self=false}) {
    const C=window.PrototypeClinicInfo;
    const [d,set]=useState(()=>C.defaults({name:'',subject:'',address:'',contact:'',phone:'',rep:'',hours:'09:00–18:00',files:[],...C.editorDraft(clinic||{})})),[error,setError]=useState(''),[reading,setReading]=useState(false);
    const put=(k,v)=>set({...d,[k]:v,...(k==='address'?{location:null}:{})});
    const submit=()=>{if(reading){setError('请等待展示图片读取完成。');return}const err=C.validate(d)||(clinic?C.commit(clone(clinic),d):null);if(err){setError(err);return}if((self?['name','address']:['name','subject','address','contact','rep']).some(k=>!String(d[k]||'').trim())||!/^1\d{10}$/.test(d.phone||'')){setError('请填写门诊名称、经营主体、持证地址、联系人、11位前台预约手机号和负责业务员。');return}onSave(d)};
    return h(Drawer,{escToExit:false,visible:true,title:clinic?'维护门诊资料':'录入签约门诊',width:760,maskClosable:false,onCancel:()=>Modal.confirm({title:'放弃未保存资料？',onOk:onCancel}),footer:h('div',{className:'flow-actions'},button(C.approved(clinic)?'提交变更审核':'保存门诊资料',submit,{type:'primary',disabled:reading}))},notice(self?'仅维护本门诊。已审核资料的任何修改均提交平台审核，通过前仍使用原信息。':'先保存资料，补齐资质和照片后在门诊内提交审核；合同与优惠无需到其他菜单办理。'),error&&notice(error,'error'),h('div',{className:'flow-form-grid'},...[["name","门诊名称"],["subject","经营主体"]].filter(([key])=>!self||key!=='rep').map(([key,label])=>field(label,h(Input,{value:d[key]||'',onChange:v=>put(key,v)})))),field('持证经营地址',h(Input,{value:d.address,onChange:v=>put('address',v),placeholder:'省市区、道路门牌、楼层铺位'})),h(C.LocationFields,{key:d.address,draft:d,onChange:set}),h('div',{className:'flow-form-grid'},...[["contact","门诊联系人"],["phone","前台预约手机号"],["rep","负责业务员"],["hours","营业时间"]].filter(([key])=>!self||key!=='rep').map(([key,label])=>field(label,h(Input,{value:d[key]||'',onChange:v=>put(key,v)})))),h(C.Fields,{draft:d,onChange:set,onBusy:setReading}),!self&&h(Files,{files:d.files,onChange:v=>put('files',v)}),!self&&button('补齐演示资质与照片',()=>put('files',[...d.files,sample('营业执照','营业执照'),sample('医疗机构执业许可证','医疗机构执业许可证'),sample('门诊环境照片','门诊照片')])));
  }
  function ContractForm({clinic,previous,onSave,onCancel}) {
    const [draft,setDraft]=useState(()=>({...makeContract(clinic,0,'待审核'),...previous,id:uid('SF'),number:previous?previous.number+'-续签':'',signed:TODAY,start:previous?nextDay(previous.end):TODAY,end:previous?String(Number(previous.end.slice(0,4))+1)+previous.end.slice(4):'2026-12-31',version:Math.max(0,...clinic.contractVersions.map(c=>c.version||0))+1,files:[],history:[],status:'待审核'})),[error,setError]=useState('');
    const put=(k,v)=>setDraft({...draft,[k]:v});
    const submit=()=>{if(!draft.number.trim()||!draft.start||!draft.end||draft.start>draft.end||!draft.signed||!draft.contact.trim()||!/^1\d{10}$/.test(draft.phone)||!draft.files.length||draft.files.some(f=>!fileOK(f))){setError('请填写合同编号、有效日期、联系人和11位手机号，并上传可读取的签署附件。');return}if(clinic.contractVersions.some(c=>active(c)&&draft.start<=c.end)){setError('新版本生效日期与当前有效合同重叠，请从旧合同到期后开始。');return}onSave(draft)};
    return h(Drawer,{escToExit:false,visible:true,title:previous?'续签门诊三方合同':'签订门诊三方合同',width:760,maskClosable:false,onCancel:()=>Modal.confirm({title:'放弃本次填写？',onOk:onCancel}),footer:h('div',{className:'flow-actions'},button('返回',()=>Modal.confirm({title:'放弃本次填写？',onOk:onCancel})),button('提交平台审核',submit,{type:'primary'}))},notice('签约主体已绑定当前门诊和渠道，渠道只能提交，审核通过后按生效日期启用。'),details([['平台',draft.platform],['渠道',draft.channel],['门诊',draft.clinic],['版本',draft.version]]),error&&notice(error,'error'),h('div',{className:'flow-form-grid'},field('合同编号',h(Input,{value:draft.number,onChange:v=>put('number',v)})),field('签订日期',h(DatePicker,{value:draft.signed,onChange:v=>put('signed',v)})),field('生效日期',h(DatePicker,{value:draft.start,onChange:v=>put('start',v)})),field('到期日期',h(DatePicker,{value:draft.end,onChange:v=>put('end',v)})),field('结算周期',h(Select,{value:draft.cycle,onChange:v=>put('cycle',v),options:['周结','月结']})),field('财务联系人',h(Input,{value:draft.contact,onChange:v=>put('contact',v)})),field('财务联系手机号',h(Input,{value:draft.phone,onChange:v=>put('phone',v)}))),notice(draft.cycle==='周结'?'周一出上周账，出账次日起3个自然日内付款。':'每月1日出上月账，出账次日起5个自然日内付款。'),h(Files,{files:draft.files,onChange:v=>put('files',v)}));
  }
  function Clinics({pages,save,focusId,focusTab,onClose}) {
    const role=window.PROTOTYPE.role,[selected,setSelected]=useState(focusId||null),[tab,setTab]=useState(focusTab||'资料与资质'),[form,setForm]=useState(null),[reason,setReason]=useState(''),[error,setError]=useState('');
    const list=rows(pages,'clinics').filter(c=>role!=='channel'||c.channel===window.PROTOTYPE.org),clinic=list.find(c=>c.id===selected),[material,setMaterial]=useState(null),[serviceTarget,setServiceTarget]=useState(null);
    const change=(label,fn)=>{const next=clone(pages);fn(rows(next,'clinics'));audit(next,label,selected);save(next);setError('')};
    const open=c=>{setSelected(c.id);setTab('资料与资质');setReason('');setError('');setMaterial(null)};
    const offersFor=c=>{const catalog=rows(pages,'schemes').length?rows(pages,'schemes'):(window.PROTOTYPE.schemeCatalog||[]);return rows(pages,'contractSchemes').filter(t=>rows(pages,'contracts').some(ct=>ct.id===t.contract&&ct.type==='平台—渠道公司'&&ct.party===c.channel&&active(ct))).map(t=>{const s=catalog.find(x=>x.name===t.scheme);return {id:t.id,scheme:t.scheme,fee:s?.fee,quantity:s?.quantity||1,status:c.schemeStates[t.scheme]||'已下线',access:t.status==='已启用'&&s?.status==='已启用',authorization:t.status==='已启用'&&s?.status==='已启用'?'当前可用':'授权或方案停用'};})};
    const review=(contract,pass)=>{if(!reason.trim()){setError('请填写审核意见。');return}if(pass&&(clinic.qualification!=='审核通过'||!contract.files.length||contract.files.some(f=>!fileOK(f)))){setError('资质未通过或签署附件缺失/不可读，不能通过合同审核。');return}if(pass&&clinic.contractVersions.some(c=>c.id!==contract.id&&['已生效','已审核待生效'].includes(c.status)&&c.start<=contract.end&&contract.start<=c.end)){setError('合同有效期与已审核版本重叠，不能通过。');return}Modal.confirm({title:pass?'通过三方合同审核？':'退回三方合同？',content:reason,onOk:()=>change('三方合同审核',all=>{const c=all.find(c=>c.id===selected).contractVersions.find(c=>c.id===contract.id);c.status=pass?(c.start>TODAY?'已审核待生效':'已生效'):'审核不通过';c.history.push({id:uid('REVIEW'),name:reason,status:c.status,date:TODAY});setReason('')})})};
    const content=clinic&&h('div',{className:'clinic-context'},notice(clinic.name+' · '+clinic.channel+' · '+clinic.id),h(Tabs,{activeTab:tab,onChange:v=>{setTab(v);setError('');setReason('')},overflow:'scroll',destroyOnHide:false},...['资料与资质','合同与续签','推广产品','账单','操作记录'].map(name=>h(Tabs.TabPane,{key:name,title:name},name===tab&&h(React.Fragment,null,
      error&&notice(error,'error'),
      name==='资料与资质'&&h(React.Fragment,null,details([['门诊',clinic.name],['持证地址',clinic.address],['负责业务员',clinic.rep||'陈宁（演示）'],['资质审核',tag(clinic.qualification)],['服务状态',tag(clinic.status)],['所属渠道',clinic.channel]]),role==='channel'&&window.PrototypeClinicInfo.permitted(clinic)&&button('维护门诊资料',()=>setForm({manage:true}),{type:'primary',disabled:window.PrototypeClinicInfo.waiting(clinic)||clinic.qualification==='待审核'}),h(window.PrototypeClinicInfo.Summary,{clinic}),h(window.PrototypeClinicInfo.Reviews,{clinic,onSave:updated=>change('审核门诊资料变更',all=>Object.assign(all.find(c=>c.id===selected),updated))}),h(Files,{files:material||clinic.files,onChange:role==='channel'&&!window.PrototypeClinicInfo.approved(clinic)&&clinic.qualification!=='待审核'?setMaterial:null}),role==='channel'&&!window.PrototypeClinicInfo.approved(clinic)&&clinic.qualification!=='待审核'&&button('提交资料审核',()=>{const f=material||clinic.files;if(!['营业执照','医疗机构执业许可证','门诊照片'].every(k=>f.some(x=>x.kind===k))||f.some(x=>!fileOK(x))){setError('请补齐可读取的门诊资质及展示附件。');return}change('门诊资料提交',all=>{const c=all.find(c=>c.id===selected);c.files=f;c.qualification='待审核';c.status='待审核'});setMaterial(null)},{type:'primary'}),role==='platform'&&clinic.qualification==='待审核'&&h(React.Fragment,null,field('审核意见',h(Input.TextArea,{value:reason,onChange:setReason})),button('资质审核通过',()=>{if(!reason.trim()||!['营业执照','医疗机构执业许可证','门诊照片'].every(k=>clinic.files.some(f=>f.kind===k))||clinic.files.some(f=>!fileOK(f))){setError('请填写意见并核对所有可读取的资质与照片。');return}change('资质审核通过',all=>{const c=all.find(c=>c.id===selected);c.qualification='审核通过';c.status='审核通过';c.needsReview=false;c.history.push(reason)})},{type:'primary'}),button('退回资料',()=>{if(!reason.trim()){setError('请填写退回原因。');return}change('退回门诊资料',all=>{const c=all.find(c=>c.id===selected);c.qualification='审核不通过';c.status='审核不通过';c.history.push(reason)})},{status:'danger'}))),
      name==='合同与续签'&&h(React.Fragment,null,h(PrototypeRules.Cycle,{clinic,pages,save}),notice('三方签署：平台 / 当前渠道公司 / 门诊。旧有效合同在新版本审核及生效前继续有效。'),role==='channel'&&button(clinic.contractVersions.some(active)?'发起续签':'签订三方合同',()=>{if(clinic.contractVersions.some(c=>['待审核','已审核待生效'].includes(c.status))){setError('已有待审核或待生效版本，请先处理现有版本。');return}setForm({previous:clinic.contractVersions.find(active)||null})},{type:'primary'}),h(RecordList,{items:clinic.contractVersions,states:['待审核','已生效','已审核待生效','审核不通过','已到期'],columns:[['number','合同编号'],['version','版本'],['start','生效日期'],['end','到期日期'],['cycle','账期'],['status','状态']],actions:c=>button('查看合同材料',()=>setForm({view:c}),{type:'text'})}),...clinic.contractVersions.filter(c=>c.status==='待审核'&&role==='platform').map(c=>section('待审合同 '+c.number,h(Files,{files:[...clinic.files,...c.files]}),field('合同审核意见',h(Input.TextArea,{value:reason,onChange:setReason})),h('div',{className:'flow-actions'},button('通过合同审核',()=>review(c,true),{type:'primary'}),button('退回合同',()=>review(c,false),{status:'danger'}))))),
      name==='推广产品'&&h(React.Fragment,null,notice('默认列出渠道合同可用方案，尚未配置的默认下线；上下线不修改方案或费率。'),h(RecordList,{items:offersFor(clinic),states:['已上线','已下线'],columns:[['scheme','方案'],['quantity','单次份数'],['fee','获客费（元）'],['authorization','上游授权'],['status','门诊上线状态']],actions:r=>button(r.status==='已上线'?'下线':'上线',()=>{if(r.status!=='已上线'&&(!r.access||clinic.qualification!=='审核通过'||!clinic.contractVersions.some(active)||/暂停|冻结|终止|退出/.test(clinic.status))){setError('授权、门诊资质、有效三方合同或服务状态不满足，不能上线。');return}change('门诊优惠'+(r.status==='已上线'?'下线':'上线'),all=>{all.find(c=>c.id===selected).schemeStates[r.scheme]=r.status==='已上线'?'已下线':'已上线'})},{type:'text'})})),
      name==='操作记录'&&h(PrototypeManagement.Logs,{record:clinic}),
      name==='账单'&&h(RecordList,{items:rows(pages,'bills').filter(b=>b.name===clinic.name),states:['待付款','付款待确认','已逾期','已结清'],columns:[['period','账期'],['amount','应付（元）'],['deadline','截止'],['status','状态']],exportName:clinic.name+'账单'})
    )))));
    return h(React.Fragment,null,!focusId&&role==='channel'&&h('div',{className:'flow-actions'},button('录入签约门诊',()=>{setForm({create:true})},{type:'primary'})),!focusId&&h(RecordList,{items:list,states:['草稿','待审核','审核通过','服务中','审核不通过','已暂停'],columns:[['name','门诊名称'],['address','经营地址'],['rep','负责业务员'],['status','状态']],onView:open,actions:role==='platform'?c=>button(['正常','服务中','审核通过'].includes(c.status)?'下线':'上线',()=>setServiceTarget(c),{type:'text'}):null}),
      serviceTarget&&h(PrototypeManagement.ServiceDialog,{clinic:serviceTarget,pages,onSave:save,onClose:()=>setServiceTarget(null)}),
      clinic&&h(Drawer,{escToExit:false,title:clinic.name+' · 门诊管理',visible:true,width:1000,footer:null,onCancel:()=>{setSelected(null);onClose?.()}},content),
      (form?.create||form?.manage)&&h(ClinicInfoForm,{clinic:form.manage?clinic:null,onCancel:()=>setForm(null),onSave:d=>{if(form.manage&&!window.PrototypeClinicInfo.permitted(clinic)){setError('只能维护本渠道管理的门诊。');return}const targetId=form.manage?selected:uid('MZ');change('保存门诊资料',all=>{if(form.manage){const c=all.find(c=>c.id===selected);const err=window.PrototypeClinicInfo.commit(c,d);if(err)throw Error(err);}else all.push({...d,ownerUserId:PrototypeManagement.session()?.id,timeout:24,id:targetId,channel:window.PROTOTYPE.org,qualification:'草稿',status:'草稿',flowVersion:18,contractVersions:[],schemeStates:{},history:[]})});setForm(null);setSelected(targetId);setTab('资料与资质')}}),
      form&&!form.create&&!form.manage&&!form.view&&h(ContractForm,{clinic,previous:form.previous,onCancel:()=>setForm(null),onSave:d=>{change('提交三方合同',all=>all.find(c=>c.id===selected).contractVersions.push(d));setForm(null)}}),
      form?.view&&h(Drawer,{escToExit:false,visible:true,title:'三方合同材料与记录',width:780,footer:null,onCancel:()=>setForm(null)},details([['合同编号',form.view.number],['平台',form.view.platform],['渠道',form.view.channel],['门诊',form.view.clinic],['生效日期',form.view.start],['到期日期',form.view.end],['付款方',form.view.payer],['收款方',form.view.payee],['周期',form.view.cycle],['状态',tag(form.view.status)]]),h(Files,{files:[...clinic.files,...form.view.files]}),h(RecordList,{items:form.view.history,states:['已生效','已审核待生效','审核不通过'],columns:[['name','审核意见'],['date','日期'],['status','结论']]})));
  }
  const due = b => Math.max(0,Math.round((b.amount-b.confirmed)*100)/100);
  const billStatus = b => b.status==='已取消'?'已取消':due(b)===0?'已结清':b.deadline<TODAY?'已逾期':b.receipts.some(r=>r.status==='待审核')||b.attempts.some(a=>['待支付','结果待核实'].includes(a.status))?'付款待确认':b.status==='有异议'?'有异议':'待付款';
  function Bills({pages,save,focusId,onClose}) {
    const role=window.PROTOTYPE.role,[id,setId]=useState(focusId||null),[action,setAction]=useState(null),[reason,setReason]=useState(''),[amount,setAmount]=useState(0),[date,setDate]=useState(TODAY),[payer,setPayer]=useState(''),[files,setFiles]=useState([]),[error,setError]=useState('');
    const list=rows(pages,'bills').map(b=>({...b,status:billStatus(b)})),bill=list.find(b=>b.id===id),pending=bill?.attempts.find(a=>['待支付','结果待核实'].includes(a.status));
    const change=(label,fn)=>{const next=clone(pages),b=rows(next,'bills').find(b=>b.id===id);const wasPaid=billStatus(b)==='已结清';fn(b);b.status=billStatus(b);if(!wasPaid&&b.status==='已结清')b.settledAt=TODAY;b.history.unshift({id:uid('EVENT'),name:label,date:TODAY,status:'已记录'});audit(next,label,id);save(next);setError('')};
    const open=b=>{setId(b.id);setAction(null);setError('');setReason('')};
    const online=()=>{if(bill.receipts.some(r=>r.status==='待审核')){setError('线下凭证尚待审核，不能同时发起在线支付。');return}if(!due(bill)){setError('账单已结清，不能重复支付。');return}if(!pending)change('创建微信支付演示订单',b=>b.attempts.unshift({id:uid('PAY'),amount:due(b),revision:b.revision,status:'待支付'}));setAction('online')};
    const result=(success)=>{change(success?'模拟可信查单：支付成功':'模拟查单：结果仍未确认',b=>{const a=b.attempts.find(a=>['待支付','结果待核实'].includes(a.status));if(!a)return;if(success){if(a.revision!==b.revision||Math.abs(a.amount-due(b))>0.001){a.status='结果待核实';b.history.unshift({id:uid('ERR'),name:'账单金额或版本变化，须核实资金',date:TODAY,status:'待处理'});return}a.status='支付成功';b.confirmed+=a.amount;b.receipts.unshift({id:a.id,amount:a.amount,date:TODAY,payer:'微信付款人（演示）',status:'已通过',channel:'微信支付',files:[]})}else a.status='结果待核实'})};
    const submit=()=>{if(!Number.isFinite(amount)||amount<=0||amount>due(bill)||!date||!payer.trim()||!files.length||files.some(f=>!fileOK(f))){setError('请填写不超过剩余应付的付款金额、日期、付款方和可读取凭证。');return}if(pending){setError('在线支付结果未决，先查单或确认关闭订单。');return}change('提交付款凭证',b=>b.receipts.unshift({id:uid('REC'),amount,date,payer,status:'待审核',files:clone(files)}));setAction(null)};
    const review=(r,pass)=>{if(!reason.trim()){setError('请填写收款审核意见。');return}if(pass&&(pending||!r.files.length||r.files.some(f=>!fileOK(f)))){setError('存在未决支付或凭证不可读，不能确认到账。');return}Modal.confirm({title:pass?'确认已核实实际到账？':'退回付款凭证？',content:reason,onOk:()=>change(pass?'确认线下到账':'退回付款凭证',b=>{const item=b.receipts.find(x=>x.id===r.id);if(item.status!=='待审核')return;if(pass&&item.amount>due(b)){item.status='待处理';item.reason='重复或超额收款，需核查';return}item.status=pass?'已通过':'已退回';item.reason=reason;if(pass)b.confirmed+=item.amount;setReason('')})})};
    return h(React.Fragment,null,notice('预约不计费、核销记账，按合同周结/月结。扫码支付仅模拟，不收取真实款项。'),!focusId&&h(RecordList,{items:list,states:['待付款','付款待确认','有异议','已逾期','已结清'],columns:[['name','门诊'],['period','账期'],['amount','应付（元）'],['deadline','付款截止'],['status','状态']],onView:open,exportName:'门诊账单'}),
      bill&&h(Drawer,{escToExit:false,visible:true,title:'账单详情 · '+bill.name,width:920,footer:null,onCancel:()=>{setId(null);setAction(null);onClose?.()}},details([['账单编号',bill.id],['账期',bill.period],['应付金额',money(bill.amount)+'元'],['已确认收款',money(bill.confirmed)+'元'],['剩余应付',money(due(bill))+'元'],['付款截止',bill.deadline],['账单状态',tag(bill.status)],['收款方','齿慧通运营主体（演示）']]),notice('周结出账次日起3个自然日、月结5个自然日。全额确认才结清；逾期仅提醒，由平台人工决定上下线，付款不自动恢复人工下线。'),error&&!action&&notice(error,'error'),
        role==='clinic'&&due(bill)>0&&h('div',{className:'flow-actions'},button('上传付款凭证',()=>{if(pending||bill.receipts.some(r=>r.status==='待审核')){setError('已有付款处理中，请先等待审核或核实在线订单。');return}setAction('voucher');setAmount(due(bill));setFiles([]);setPayer(bill.name)},{type:'primary'}),button('微信扫码支付',online)),
        role==='channel'&&h(React.Fragment,null,notice('仅查看收款进度并催收，不能代门诊付款或确认到账。'),button('记录催收',()=>{setReason('');setAction('collection')})),
        section('核销与费用明细',bill.items?h(window.PrototypeOperations.TransactionList,{statement:bill,feeOnly:true}):notice('历史汇总缺少逐笔交易，请补充原始明细；完整演示请查看“演示逐笔账单”。','warning')),
        section('付款凭证与审核记录',h(RecordList,{items:bill.receipts,states:['待审核','已通过','已退回','待处理'],columns:[['id','付款记录'],['payer','付款方'],['amount','金额（元）'],['date','付款日期'],['reason','审核意见'],['status','审核状态']],actions:r=>button('查看凭证',()=>setAction({receipt:r.id}),{type:'text'})})),
        section('在线支付订单',h(RecordList,{items:bill.attempts,states:['待支付','结果待核实','支付成功','已关闭'],columns:[['id','订单'],['amount','金额（元）'],['status','支付状态']],actions:role==='clinic'?r=>['待支付','结果待核实'].includes(r.status)&&button('继续查询',()=>setAction('online'),{type:'text'}):null})),
        h(PrototypeManagement.Logs,{record:bill}),
        action==='collection'&&h(Modal,{visible:true,title:'记录催收',okText:'保存记录',onCancel:()=>setAction(null),onOk:()=>{if(!reason.trim()){setError('请填写催收记录。');return}change('催收：'+reason,()=>{});setAction(null);setReason('')}},error&&notice(error,'error'),field('催收内容',h(Input.TextArea,{value:reason,onChange:setReason}))),
        action==='voucher'&&h(Modal,{visible:true,title:'上传付款凭证',maskClosable:false,style:{width:720,maxWidth:'95vw'},onCancel:()=>setAction(null),onOk:submit,okText:'提交审核'},notice('仅登记付款，不代表平台已经确认到账。请使用演示材料。'),error&&notice(error,'error'),field('本次付款金额（元）',h(InputNumber,{value:amount,onChange:setAmount,min:0.01,precision:2})),field('付款日期',h(DatePicker,{value:date,onChange:setDate})),field('付款方',h(Input,{value:payer,onChange:setPayer})),h(Files,{files,onChange:setFiles})),
        action==='online'&&h(Modal,{visible:true,title:'微信扫码支付 · 演示',footer:null,onCancel:()=>setAction(null),style:{maxWidth:'95vw'}},notice('不可支付的视觉示意，没有真实商户订单或资金往来。','warning'),pending?h(React.Fragment,null,details([['门诊',bill.name],['应付',money(pending.amount)+'元'],['订单',pending.id],['状态',pending.status]]),h('div',{className:'payment-code','aria-label':'不可支付的二维码示意'},h('span',null,'演示 · 不可支付')),h('div',{className:'flow-actions'},button('模拟查询：支付成功',()=>result(true),{type:'primary'}),button('模拟查询：结果未知',()=>result(false)),button('模拟确认关闭/过期',()=>change('模拟查单确认订单已关闭',b=>{b.attempts.find(a=>a.id===pending.id).status='已关闭'})))):h(React.Fragment,null,notice(bill.status==='已结清'?'支付结果已确认（演示），账单已结清。':'订单已关闭，可重新生成二维码。',bill.status==='已结清'?'success':'info'),bill.status!=='已结清'&&button('重新生成演示二维码',online))),
        action?.receipt&&(()=>{const r=bill.receipts.find(r=>r.id===action.receipt);return h(Modal,{visible:true,title:'付款凭证与审核',footer:null,style:{width:760,maxWidth:'95vw'},onCancel:()=>setAction(null)},details([['付款方',r.payer],['金额',money(r.amount)],['状态',tag(r.status)],['审核意见',r.reason||'—']]),h(Files,{files:r.files}),error&&notice(error,'error'),role==='platform'&&r.status==='待审核'&&h(React.Fragment,null,field('收款审核意见',h(Input.TextArea,{value:reason,onChange:setReason})),h('div',{className:'flow-actions'},button('确认实际到账',()=>review(r,true),{type:'primary'}),button('退回凭证',()=>review(r,false),{status:'danger'}))))})()));
  }
  function View({current,pages,save}) {
    return h('div',{className:'workflow'},h('div',{className:'page-heading'},h('div',null,h('h1',null,current.title),h('p',null,current.description))),current.custom==='clinicProfile'?h(window.PrototypeClinicInfo.Profile,{pages,save,Editor:ClinicInfoForm}):current.custom==='partner'?h(Partner,{pages}):current.custom==='clinics'?h(Clinics,{pages,save}):current.custom==='bills'?h(Bills,{pages,save}):section('本门诊三方合同',...rows(pages,'contracts').filter(r=>r.type==='三方合同').map(c=>h('div',{key:c.id},details([['合同编号',c.number],['平台',c.platform],['渠道',c.channel],['门诊',c.clinic],['生效日期',c.start],['到期日期',c.end],['结算周期',c.cycle],['状态',tag(c.status)]]),h(Files,{files:c.files}))),notice('由渠道负责签订和续签，平台审核；门诊仅查看。')));
  }
  return {prepare,migrate,View,Files,billStatus,RecordList,Clinics,Bills,field,fileOK,audit,sample};
})();
