from django.urls import path

from . import api
from . import api_appointments as appointments
from . import api_audit as audit
from . import api_catalog as catalog
from . import api_finance as finance
from . import api_location as location
from . import api_mini as mini
from . import api_metrics as metrics
from . import api_notifications as notifications
from . import api_payments as payments
from . import api_sales as sales
from . import api_workbench as workbench

urlpatterns = [
    path("health", api.health),
    path("auth/code", api.send_code),
    path("auth/login", api.login),
    path("auth/logout", api.logout),
    path("auth/me", api.me),
    path("organizations", api.organization_list),
    path("organizations/<uuid:org_id>", api.organization_detail),
    path("organizations/<uuid:org_id>/review", api.organization_review),
    path("organizations/<uuid:org_id>/resubmit", api.organization_resubmit),
    path("organizations/<uuid:org_id>/status", api.organization_status),
    path("organizations/<uuid:org_id>/members", api.member_list),
    path("members/<uuid:member_id>", api.member_update),
    path("products", catalog.product_list),
    path("products/<uuid:product_id>", catalog.product_update),
    path("organizations/<uuid:org_id>/source-brands", catalog.brand_list),
    path("organizations/<uuid:org_id>/cooperation", catalog.cooperation),
    path("files", catalog.upload),
    path("files/<uuid:asset_id>", catalog.download),
    path("organizations/<uuid:org_id>/contracts", catalog.contract_list),
    path("contract-versions/<uuid:version_id>/submit", catalog.contract_submit),
    path("contract-versions/<uuid:version_id>", catalog.contract_detail),
    path("contract-versions/<uuid:version_id>/terminate", catalog.contract_terminate),
    path("contract-versions/<uuid:version_id>/review", catalog.contract_review),
    path("contract-versions/<uuid:version_id>/products", catalog.contract_products),
    path("clinics", catalog.clinic_list),
    path("clinics/geocode", location.locate),
    path("clinics/<uuid:clinic_id>", catalog.clinic_detail),
    path("clinics/<uuid:clinic_id>/profile-changes", catalog.profile_changes),
    path("profile-changes/<uuid:change_id>/review", catalog.profile_review),
    path("clinics/<uuid:clinic_id>/service-status", catalog.clinic_service),
    path("clinics/<uuid:clinic_id>/confirmation-hours", catalog.clinic_hours),
    path("clinics/<uuid:clinic_id>/channel", catalog.clinic_channel),
    path("clinics/<uuid:clinic_id>/products", catalog.clinic_products),
    path("sales-orders", sales.orders),
    path("sales-orders/<uuid:order_id>", sales.order_detail),
    path("sales-orders/<uuid:order_id>/rows", sales.order_rows),
    path("sales-orders/<uuid:order_id>/receipts", sales.receipts),
    path("purchase-receipts/<uuid:receipt_id>/review", sales.receipt_review),
    path("sales-orders/<uuid:order_id>/cards", sales.cards),
    path("sales-orders/<uuid:order_id>/cards/export", sales.export_cards),
    path("sales-orders/<uuid:order_id>/<str:action>", sales.order_action),
    path("cards/<uuid:card_id>/freeze", sales.freeze_card),
    path("imports", sales.import_list),
    path("imports/<uuid:batch_id>", sales.import_detail),
    path("imports/<uuid:batch_id>/mapping", sales.import_mapping),
    path("imports/<uuid:batch_id>/confirm", sales.import_confirm),
    path("imports/<uuid:batch_id>/rows", sales.import_rows),
    path("imports/<uuid:batch_id>/errors.xlsx", sales.import_errors),
    path("imports/<uuid:batch_id>/suggest", sales.import_suggest),
    path("import-formats", sales.import_formats),
    path("clinic-bills", finance.clinic_bills),
    path("clinic-bills/<uuid:bill_id>", finance.clinic_bill_detail),
    path("clinic-bills/<uuid:bill_id>/lines", finance.clinic_bill_lines),
    path("clinic-bills/<uuid:bill_id>/export.xlsx", finance.clinic_bill_export),
    path("clinic-bills/<uuid:bill_id>/receipts", finance.clinic_receipts),
    path("clinic-bills/<uuid:bill_id>/feedback", finance.bill_feedback),
    path("clinic-bills/<uuid:bill_id>/collection-note", finance.collection_note),
    path("clinic-receipts/<uuid:receipt_id>/review", finance.receipt_review),
    path("partner-bills", finance.partner_bills),
    path("partner-bills/<uuid:bill_id>", finance.partner_bill_detail),
    path("partner-bills/<uuid:bill_id>/lines", finance.partner_bill_lines),
    path("partner-bills/<uuid:bill_id>/export.xlsx", finance.partner_bill_export),
    path("partner-bills/<uuid:bill_id>/feedback", finance.bill_feedback, {"partner": True}),
    path("partner-bills/<uuid:bill_id>/<str:action>", finance.partner_bill_action),
    path("settlement-details", finance.partner_bill_lines),
    path("settlement-details/export.xlsx", finance.own_partner_export),
    path("finance-feedback/<uuid:feedback_id>/respond", finance.feedback_response),
    path("appointments", appointments.appointment_list),
    path("appointments/export.xlsx", appointments.appointment_export),
    path("appointments/reminder-snapshot", appointments.reminder_snapshot),
    path("appointments/<uuid:appointment_id>", appointments.appointment_detail),
    path("appointments/<uuid:appointment_id>/<str:action>", appointments.appointment_action),
    path("reschedules", appointments.reschedules),
    path("reschedules/<uuid:change_id>/review", appointments.reschedule_review),
    path("redemptions/scan", appointments.scan),
    path("redemptions/quote", appointments.redemption_quote),
    path("redemptions", appointments.redeem),
    path("redemptions/<uuid:redemption_id>/reverse", appointments.reverse_redemption),
    path("fulfillment-tasks", appointments.fulfillment_tasks),
    path("clinic-bills/<uuid:bill_id>/payments", payments.bill_payments),
    path("payments/configuration", payments.payment_configuration),
    path("payments/<uuid:attempt_id>/<str:action>", payments.payment_action),
    path("payments/wechat/notify", payments.notification),
    path("notifications", notifications.notification_list),
    path("notifications/<uuid:notification_id>/read", notifications.notification_read),
    path("sms-templates", notifications.templates),
    path("sms-templates/<str:code>", notifications.configure_template),
    path("sms-deliveries", notifications.sms_deliveries),
    path("sms-deliveries/<uuid:delivery_id>/attempts", notifications.sms_history),
    path("jobs", notifications.jobs),
    path("jobs/<uuid:job_id>/retry", notifications.retry_job),
    path("calendar", notifications.calendar_list),
    path("calendar/<str:date>", notifications.calendar_day),
    path("workbench", workbench.overview),
    path("workbench/tasks", workbench.tasks),
    path("workbench/tasks/<str:category>/<uuid:object_id>", workbench.task_detail),
    path("objects/<str:object_type>/<uuid:object_id>/logs", audit.object_log),
    path("customer-overview", metrics.overview),
    path("customer-overview/products", metrics.products),
    path("customer-overview/trend", metrics.trend),
    path("customer-overview/details", metrics.details),
    path("customer-overview/customer-cards", metrics.details, {"customer_cards": True}),
    path("customer-overview/export.xlsx", metrics.export),
    path("mini/customer/login", mini.mini_login, {"audience": "customer"}),
    path("mini/customer/me", mini.me),
    path("mini/customer/logout", api.logout),
    path("mini/customer/profile", mini.profile),
    path("mini/customer/benefits", mini.benefits),
    path("mini/customer/cards/<uuid:card_id>/claim", mini.claim),
    path("mini/customer/cards/activate", mini.activate),
    path("mini/customer/appointments", mini.appointment_list),
    path("mini/customer/appointments/<uuid:appointment_id>", mini.appointment_detail),
    path("mini/customer/appointments/<uuid:appointment_id>/<str:action>", mini.appointment_action),
    path("mini/customer/messages", mini.messages),
    path("mini/customer/messages/<uuid:message_id>/read", mini.message_read),
    path("mini/clinic/login", mini.mini_login, {"audience": "clinic"}),
    path("mini/clinic/me", mini.me),
    path("mini/clinic/logout", api.logout),
    path("mini/clinic/workbench", workbench.overview),
    path("mini/clinic/workbench/tasks", workbench.tasks),
    path("mini/clinic/workbench/tasks/<str:category>/<uuid:object_id>", workbench.task_detail),
    path("mini/clinic/appointments", appointments.appointment_list),
    path("mini/clinic/appointments/<uuid:appointment_id>", appointments.appointment_detail),
    path("mini/clinic/appointments/<uuid:appointment_id>/<str:action>", appointments.appointment_action),
    path("mini/clinic/reschedules", appointments.reschedules),
    path("mini/clinic/reschedules/<uuid:change_id>/review", appointments.reschedule_review),
    path("mini/clinic/redemptions/scan", appointments.scan),
    path("mini/clinic/redemptions/quote", appointments.redemption_quote),
    path("mini/clinic/redemptions", appointments.redeem),
    path("mini/clinic/redemptions/<uuid:redemption_id>/reverse", appointments.reverse_redemption),
    path("mini/clinic/fulfillment-tasks", appointments.fulfillment_tasks),
    path("mini/clinic/bills", finance.clinic_bills),
    path("mini/clinic/bills/<uuid:bill_id>", finance.clinic_bill_detail),
    path("mini/clinic/bills/<uuid:bill_id>/lines", finance.clinic_bill_lines),
    path("mini/clinic/bills/<uuid:bill_id>/receipts", finance.clinic_receipts),
    path("mini/clinic/bills/<uuid:bill_id>/payment", mini.clinic_payment),
    path("mini/clinic/bills/<uuid:bill_id>/feedback", finance.bill_feedback, {"partner": False}),
    path("mini/clinic/payments/<uuid:attempt_id>/<str:action>", payments.payment_action),
    path("mini/clinic/organizations/<uuid:org_id>/cooperation", catalog.cooperation),
    path("mini/clinic/organizations/<uuid:org_id>/contracts", catalog.contract_list),
    path("mini/clinic/contracts/<uuid:version_id>", catalog.contract_detail),
    path("mini/clinic/files", catalog.upload),
    path("mini/clinic/files/<uuid:asset_id>", catalog.download),
    path("mini/clinic/notifications", notifications.notification_list),
    path("mini/clinic/notifications/<uuid:notification_id>/read", notifications.notification_read),
]
