(() => {
  const {h,clone,useStore,useRoute,btn,note,field,row,card,heading,datePlus,validDate,StateList,Shell,confirm,log,today}=Mini;
  const {useState,useEffect}=React,{Input,Select,Checkbox}=arco;
  const OD=PrototypeOverdue;
  const nav=[['home','首页','⌂'],['benefits','权益','◇'],['appointments','预约','▣'],['profile','我的','○']];
  const seed={logged:false,profile:{name:'客户甲（演示）',phone:'13800000011',sex:'未填写'},cards:{'CARD-001':'未激活','CARD-USED':'已激活','CARD-VOID':'已作废','CARD-FROZEN':'已冻结'},
    benefits:[{id:'B1',name:'舒适洁牙服务',source:'安和保险客户福利',mode:'Excel导入',total:2,held:0,used:0,state:'待领取',days:180},
      {id:'B2',name:'舒适洁牙服务',source:'星海银行信用卡礼遇',mode:'Excel导入',total:1,held:0,used:0,state:'已领取',expiry:'2027-03-06'},
      {id:'B3',name:'舒适洁牙服务',source:'安和保险客户福利',mode:'不记名卡激活',total:1,held:1,used:0,state:'已领取',expiry:'2027-03-06'},
      {id:'B4',name:'舒适洁牙服务',source:'安和保险客户福利',mode:'Excel导入',total:1,held:0,used:0,state:'已领取',expiry:'2026-08-31'},
      {id:'B5',name:'种植牙专享抵用券',source:'安和保险客户福利',mode:'Excel导入',total:1,held:0,used:0,state:'已冻结',expiry:'2027-03-06'},
      {id:'B6',name:'舒适洁牙服务',source:'星海银行信用卡礼遇',mode:'Excel导入',total:1,held:1,used:0,state:'已领取',expiry:'2027-03-06'}],
    appointments:[{id:'A1',benefit:'B3',clinic:'M1',status:'成功',date:'2026-09-09',time:'10:00',intent:'2026-09-09 10:00',feedback:''},
      {id:'A2',benefit:'B6',clinic:'M1',status:'待确认',date:'2026-09-10',time:'14:00',intent:'2026-09-10 14:00',feedback:''}],
    messages:[{id:'N1',name:'您有2份洁牙权益待领取，领取后180天内有效。',status:'未读'}]};
  const clinics=[{id:'M1',name:'明禾口腔',area:'春和区',address:'演示市春和路12号',distance:'1.2km',hours:'周一至周日 09:00–18:00',active:true,schemes:['舒适洁牙服务']},
    {id:'M2',name:'映禾口腔',area:'景明区',address:'演示市景明路28号',distance:'3.6km',hours:'周一至周六 09:00–18:00',active:true,schemes:['舒适洁牙服务']},
    {id:'M3',name:'青禾口腔',area:'春和区',address:'演示市静安路9号',distance:'0.8km',active:false,schemes:['舒适洁牙服务']}];
  const available=b=>b.total-b.held-b.used-(b.pendingRestore||0);
  const benefitStatus=b=>b.state==='待领取'?'待领取':b.state==='已冻结'?'已冻结':b.expiry<today?'已过期':available(b)>0?'可使用':b.pendingRestore>0?'待恢复':b.held>0?'预约占用':'已用完';
  const usageRules=b=>b.rules||('每次使用'+(b.quantity||1)+'份；仅限已上线且适用本产品的门诊，须先预约，完成约定服务后由门诊扫码核销。');
  function AppointmentCode({a,b}){
    const reason=b.state!=='已领取'?'权益尚未领取或已冻结':!b.expiry||!a.date||a.date>b.expiry?'预约日期超过有效期或有效期缺失':a.pendingRestore>0?'补核销已撤销，权益待恢复':a.redemptionId||a.used>0?'本次预约已核销':a.status==='待确认'?'等待门诊确认预约':!['成功','完成'].includes(a.status)||a.status==='完成'&&a.completionSource!=='系统超时处理'?'本次预约不可核销':a.released||b.held<(a.quantity||1)?'关联权益已恢复或占用不足':a.change||a.changeStatus==='待确认'||a.changeStatus==='改期待确认'?'改期待确认，请先等待门诊处理':a.conflict||a.frozen||/冲突|待核实/.test(a.feedback||'')?'存在冲突或冻结，请先核实':'';
    return card('核销二维码',reason?'暂不可核销':'固定凭证',h(React.Fragment,null,row('推广产品',b.name),reason?note(reason,'warn'):h('div',{className:'credential'},h('div',{className:'qr-demo','aria-label':'预约核销二维码示意'},h('span',null,'演示凭证')),h('strong',null,'DEMO-'+b.id),h('p',null,'到诊完成服务后，请门诊扫码核销。'),note('不可真实扫码的原型示意；凭证不含手机号。实际核销须联网检查预约时间、权益状态及门诊权限。')),h('div',{className:'usage-rules'},h('strong',null,'使用规则'),h('p',null,usageRules(b)))));
  }
  function DateForm({date,time,expiry,label,onSubmit}){const [d,setD]=useState(date||'2026-09-08'),[t,setT]=useState(time||'10:00'),[error,setError]=useState('');return h('section',{className:'card'},note('最晚可预约至 '+expiry+'；提交的是意向时间，以门诊确认时间为准。'),field('预约日期',h('input',{type:'date',value:d,min:today,max:expiry,onChange:e=>setD(e.target.value)})),field('预约时间',h('input',{type:'time',value:t,onChange:e=>setT(e.target.value)})),error&&note(error,'error'),btn(label,()=>{const error=validDate(d,t,expiry);if(error)setError(error);else onSubmit(d,t)}));}
  function App(){
    const [data,save]=useStore('chihuitong-customer-mini-v1',seed,d=>OD.miniMigrate(d,'customer')),[route,go]=useRoute(),[error,setError]=useState(''),[agree,setAgree]=useState(false),[code,setCode]=useState(''),[looked,setLooked]=useState(''),[feedback,setFeedback]=useState(''),[area,setArea]=useState('全部地区'),[locationState,setLocationState]=useState('未授权定位'),[search,setSearch]=useState(''),[name,setName]=useState(data.profile.name),[sex,setSex]=useState(data.profile.sex);
    useEffect(()=>{setError('')},[route]);
    const [page,id,clinicId]=route.split('/'),b=data.benefits.find(b=>b.id===id),a=data.appointments.find(a=>a.id===id);
    const update=fn=>{const next=clone(data);fn(next);save(next)};
    const overdueRecord=a=>{const b=data.benefits.find(b=>b.id===a.benefit);return {...a,held:a.released?0:(a.held??Math.min(1,b.held)),used:a.used??0,quantity:a.quantity||1,expiry:b.expiry,externalName:b.name}};
    const overdueAction=(id,action)=>{try{const next=clone(data),item=next.appointments.find(a=>a.id===id),b=next.benefits.find(b=>b.id===item.benefit),record=overdueRecord(item),before=record.held,beforeRestore=record.pendingRestore||0;OD.act(record,action,'customer');Object.assign(item,record);b.held+=record.held-before;b.pendingRestore=(b.pendingRestore||0)+(record.pendingRestore||0)-beforeRestore;log(next,action==='restore'?'恢复申请已通过，权益已释放；有效期不变':'到诊反馈已记录，等待门诊处理（通知模拟）');save(next);}catch(e){arco.Message.error(e.message)}};
    const pending=data.benefits.filter(b=>b.state==='待领取');
    const claim=b=>confirm('领取权益',b.source+' · '+b.total+'份；领取成功起180天有效。',()=>update(d=>{const item=d.benefits.find(r=>r.id===b.id);if(item.state!=='待领取')return;item.state='已领取';item.expiry=datePlus(item.days);log(d,'已领取 '+item.source+' 的'+item.total+'份权益');}));
    const cancel=a=>{if(a.status==='成功'&&OD.elapsed(a)>=0){go('feedback/'+a.id);return}confirm('取消本次预约？','取消后释放关联权益；系统将通知门诊（本原型不发送短信）。',()=>update(d=>{const item=d.appointments.find(r=>r.id===a.id);if(!['待确认','成功'].includes(item.status))return;item.status='取消';item.reason='客户主动取消';delete item.change;d.benefits.find(r=>r.id===item.benefit).held-=1;log(d,'预约 '+item.id+' 已取消，权益已释放');}));};
    const benefitCard=b=>h('div',{key:b.id},card(b.name,benefitStatus(b),h(React.Fragment,null,h('p',{className:'muted'},b.source),row(b.state==='待领取'?'待领取数量':'剩余可用',(b.state==='待领取'?b.total:benefitStatus(b)==='可使用'?available(b):0)+'份'),row('有效期',b.state==='待领取'?'领取后180天':b.expiry),row('权益编号',b.id),b.pendingRestore>0&&row('待恢复',b.pendingRestore+'份'),h('div',{className:'usage-rules'},h('strong',null,'使用规则'),h('p',null,usageRules(b)))),b.state==='待领取'?btn('领取权益',()=>claim(b)):btn('预约门诊',()=>go('clinics/'+b.id),{disabled:benefitStatus(b)!=='可使用'})));
    const appointmentCard=a=>{const b=data.benefits.find(b=>b.id===a.benefit);return h('div',{key:a.id},card(clinics.find(c=>c.id===a.clinic).name,a.status,h(React.Fragment,null,row(a.status==='待确认'?'意向时间':'预约时间',a.date+' '+a.time),a.overdueManaged&&note(OD.summary(overdueRecord(a)),'warn'),h('p',{className:'muted'},b.name+' · '+b.source),a.change&&note('改期待确认：'+a.change.date+' '+a.change.time)),btn('预约详情',()=>go('appointment/'+a.id),{type:'secondary'})));};
    let body;
    if(!data.logged&&page!=='legal')body=h(React.Fragment,null,heading('欢迎使用齿慧通','领取您的口腔福利，预约身边的门诊'),h('div',{className:'hero'},h('h2',null,'让每一份福利，都能安心使用'),h('p',null,'同一账号查看来自不同机构的权益。登录不会自动领取或增加权益。')),note('演示手机号 138****0011；此按钮模拟微信手机号授权，不调用真实微信接口。'),h(Checkbox,{checked:agree,onChange:setAgree},'我已阅读并同意演示协议与隐私说明'),btn('查看协议与隐私说明',()=>go('legal'),{type:'text'}),error&&note(error,'error'),btn('手机号授权登录（演示）',()=>{if(!agree){setError('请先阅读并同意协议与隐私说明');return}update(d=>{d.logged=true});go('home')}));
    else if(page==='legal')body=h(React.Fragment,null,heading('协议与隐私说明'),note('这是交互评审原型，不收集真实手机号、定位或诊疗信息。请勿填写真实个人资料；所有操作只保存在本浏览器。正式用户协议与隐私政策尚待专项评审。'),btn('返回登录/首页',()=>go('home')));
    else if(page==='home')body=h(React.Fragment,null,heading('你好，'+data.profile.name,'您的口腔福利服务'),h('section',{className:'hero'},h('h2',null,'好好照顾每一次微笑'),h('p',null,'先领取权益，再选择门诊预约。'),btn('查看我的权益',()=>go('benefits'))),...data.appointments.filter(a=>a.customerPending).map(a=>card('预约结果待处理',a.status,h(React.Fragment,null,row('门诊','明禾口腔'),row('预约',a.date+' '+a.time),row('推广产品',overdueRecord(a).externalName),note(OD.summary(overdueRecord(a))+(a.pendingRestore>0?'':'。如果确实未到诊，请申请恢复权益。'),'warn')),btn('处理预约 '+a.id,()=>go('feedback/'+a.id)))),pending.length>0&&card('有待领取的福利','待领取',h('p',null,'来自合作机构的权益等待您主动领取，有效期从领取成功开始。'),btn('去领取权益',()=>go('benefits'))),h('div',{className:'count-grid'},h('button',{onClick:()=>go('benefits')},h('b',null,data.benefits.filter(b=>benefitStatus(b)==='可使用').length),'可用权益'),h('button',{onClick:()=>go('appointments')},h('b',null,data.appointments.filter(a=>['待确认','成功'].includes(a.status)).length),'进行中预约'),h('button',{onClick:()=>go('messages')},h('b',null,data.messages.filter(m=>m.status==='未读').length),'未读消息')),card('收到实体福利卡？',null,h('p',{className:'muted'},'扫码激活后即可预约，不设置激活截止日期。'),btn('扫码激活卡片',()=>go('activate'),{type:'secondary'})));
    else if(page==='benefits')body=h(React.Fragment,null,heading('我的权益','同一方案不同来源分别保留，不合并归属'),h(StateList,{states:['待领取','可使用','待恢复','预约占用','已用完','已过期','已冻结'],items:data.benefits.map(b=>({...b,status:benefitStatus(b)})),render:benefitCard}));
    else if(page==='benefit'&&b)body=h(React.Fragment,null,heading(b.name,b.source),card('权益详情',benefitStatus(b),h(React.Fragment,null,row('获得方式',b.mode),row('总份数',b.total),row('预约占用',b.held),row('已核销',b.used),row('每次使用','1份'),row('到期日期',b.expiry||'领取成功起180天'),note('仅限平台已上线且适用本权益的门诊。请先预约，完成服务后由门诊扫码核销。')),b.state==='待领取'?btn('确认领取',()=>claim(b)):benefitStatus(b)==='可使用'?btn('选择附近门诊',()=>go('clinics/'+b.id)):note('当前权益不可新建预约，请查看关联预约或联系权益来源方。','warn')),b.state!=='待领取'&&btn('查看固定权益凭证',()=>go('credential/'+b.id),{type:'secondary'}));
    else if(page==='credential'&&b&&b.state==='待领取')body=note('请先领取权益，再查看固定凭证。','warn');
    else if(page==='credential'&&b)body=h(React.Fragment,null,heading('权益凭证',b.source),note('仅为固定凭证视觉示意，不能用于真实扫码核销。'),h('div',{className:'credential'},h('h2',null,b.name),h('div',{className:'qr-demo','aria-label':'不可核销的二维码示意'},h('span',null,'演示凭证')),h('strong',null,'DEMO-'+b.id),h('p',null,benefitStatus(b)),h('p',{className:'muted'},'凭证不含手机号。门诊必须联网校验预约、权益与服务状态。')),btn('查看关联预约',()=>go('appointments'),{type:'secondary'}));
    else if(page==='activate')body=h(React.Fragment,null,heading('激活福利卡','请扫描卡片二维码后确认权益'),h('div',{className:'scan-window'},h('div',null,h('strong',null,'扫描卡片二维码'),h('span',{className:'muted'},'相机未接入 · 使用下方演示卡号'))),field('演示卡号',h(Input,{value:code,onChange:setCode,placeholder:'CARD-001'})),btn('读取演示卡片',()=>{setLooked(code.trim().toUpperCase());setError('')}),h('p',{className:'muted'},'可试用：CARD-001 / CARD-USED / CARD-VOID / CARD-FROZEN'),looked&&(data.cards[looked]==='未激活'?card('舒适洁牙服务','未激活',h(React.Fragment,null,row('来源','安和保险客户福利'),row('数量','1份'),row('有效期','激活成功起180天'),note('激活后绑定当前账号，不支持转让。未激活卡没有激活截止日期。')),btn('确认激活到我的账号',()=>confirm('确认激活？','此卡将绑定当前演示客户，不能转让。',()=>{if(data.cards[looked]!=='未激活')return;update(d=>{d.cards[looked]='已激活';d.benefits.push({id:'CARD-B1',name:'舒适洁牙服务',source:'安和保险客户福利',mode:'不记名卡激活',total:1,held:0,used:0,state:'已领取',expiry:datePlus(180)});log(d,'卡片激活成功，有效期已开始');});go('benefit/CARD-B1')}))):note(data.cards[looked]?'该卡'+data.cards[looked]+'，不能再次激活。':'未找到该演示卡，请核对卡号。','error')));
    else if((page==='clinics'||page==='clinic'||page==='booking')&&b){
      const eligible=clinics.filter(c=>c.active&&c.schemes.includes(b.name)),c=eligible.find(c=>c.id===clinicId);
      if(benefitStatus(b)!=='可使用')body=h(React.Fragment,null,heading('权益暂不可预约'),note('权益已占用、过期、冻结或尚未领取，请先查看权益状态。','warn'),btn('返回权益',()=>go('benefit/'+b.id)));
      else if(page==='clinics')body=h(React.Fragment,null,heading('选择门诊',b.name+' · '+b.source),note(locationState+'；距离仅为演示，不读取GPS。'),h('div',{className:'stack'},btn('使用演示位置',()=>setLocationState('演示位置：春和路'),{type:'secondary'}),btn('不授权，手动选地区',()=>setLocationState('已拒绝定位，请选择地区'),{type:'text'})),field('地区',h(Select,{value:area,onChange:setArea,options:['全部地区','春和区','景明区']})),field('门诊名称',h(Input,{value:search,onChange:setSearch,placeholder:'搜索门诊'})),...eligible.filter(c=>(area==='全部地区'||c.area===area)&&c.name.includes(search)).map(c=>h('div',{key:c.id},card(c.name,'可预约',h(React.Fragment,null,row('地址',c.address),row('距离',locationState.startsWith('演示')?c.distance:'定位后可查看'),row('营业时间',c.hours)),btn('查看门诊',()=>go('clinic/'+b.id+'/'+c.id))))),!eligible.some(c=>(area==='全部地区'||c.area===area)&&c.name.includes(search))&&h('div',{className:'empty'},'暂无可承接门诊，请调整地区或查询条件'));
      else if(!c)body=note('该门诊当前不能承接新的预约，请重新选择。','error');
      else if(page==='clinic')body=h(React.Fragment,null,heading(c.name,'平台审核通过 · 实名门诊'),card('门诊信息',null,h(React.Fragment,null,row('地址',c.address),row('营业时间',c.hours),row('适用权益',b.name),row('使用数量','本次1份'),note('客户提交意向时间后，门诊人工联系并确认。无可选固定号源。')),btn('预约该门诊',()=>go('booking/'+b.id+'/'+c.id))));
      else body=h(React.Fragment,null,heading('提交预约',c.name),note(b.source+' · 使用1份'+b.name),h(DateForm,{key:route,expiry:b.expiry,label:'提交意向预约',onSubmit:(date,time)=>{if(available(b)<1)return;update(d=>{const benefit=d.benefits.find(r=>r.id===b.id);if(available(benefit)<1)return;benefit.held+=1;d.appointments.unshift({id:'A-'+Date.now(),benefit:b.id,clinic:c.id,status:'待确认',date,time,intent:date+' '+time,feedback:''});log(d,'意向预约已提交，等待门诊确认；24小时未处理将自动取消（原型不运行计时任务）');});go('appointments')}}));
    }
    else if(page==='appointments')body=h(React.Fragment,null,heading('我的预约','意向时间须由门诊确认'),h(StateList,{states:['待确认','成功','完成','取消'],items:data.appointments,render:appointmentCard}));
    else if((page==='appointment'||page==='reschedule')&&a){const benefit=data.benefits.find(b=>b.id===a.benefit),clinic=clinics.find(c=>c.id===a.clinic);
      if(page==='reschedule')body=h(React.Fragment,null,heading('申请改期'),a.status!=='成功'||a.change?note('当前不可再次申请改期，请等待已有请求处理。','warn'):h(React.Fragment,null,note('门诊确认前，原预约 '+a.date+' '+a.time+' 继续有效。'),h(DateForm,{key:route,date:a.date,time:a.time,expiry:benefit.expiry,label:'提交改期申请',onSubmit:(date,time)=>{update(d=>{const item=d.appointments.find(r=>r.id===a.id);if(item.change)return;item.change={date,time,status:'待确认'};log(d,'改期申请已提交，原时间仍有效');});go('appointment/'+a.id)}})));
      else body=h(React.Fragment,null,heading(clinic.name),h(AppointmentCode,{a,b:benefit}),card('预约详情',a.status,h(React.Fragment,null,row('预约编号',a.id),row('意向时间',a.intent),row('当前时间',a.date+' '+a.time),row('权益来源',benefit.source),row('到期日期',benefit.expiry),row('取消原因',a.reason||'—'),a.change&&note('改期待确认：'+a.change.date+' '+a.change.time+'；原时间继续有效。','warn'),a.overdueManaged&&note(OD.summary(overdueRecord(a)),'warn'),a.feedback&&note('您的反馈：'+a.feedback+(a.released?'。原占用已解除。':'。以当前权益占用及核销记录为准。'))),h(React.Fragment,null,btn('联系门诊（演示）',()=>confirm('联系门诊','演示号码400-000-0000，原型不发起真实拨号。',()=>{}),{type:'secondary'}),a.status==='成功'&&!a.change&&btn('申请改期',()=>go('reschedule/'+a.id),{type:'secondary'}),(a.status==='待确认'||a.status==='成功'&&OD.elapsed(a)<0)&&btn('取消预约',()=>cancel(a),{type:'outline',status:'danger'}))),(a.status==='成功'||a.customerPending||a.overdueManaged)&&btn('预约结果与权益处理',()=>go('feedback/'+a.id),{type:'secondary'}));
    }
    else if(page==='feedback'&&a)body=h(React.Fragment,null,heading('预约结果与权益处理','明禾口腔 · '+overdueRecord(a).externalName),OD.elapsed(a)<0?note('尚未到预约时间。需要调整安排时，请申请改期或取消预约。'):h(OD.Details,{a:overdueRecord(a),role:'customer',onAction:action=>overdueAction(a.id,action)}));
    else if(page==='messages')body=h(React.Fragment,null,heading('消息通知'),h(StateList,{states:['未读','已读'],items:data.messages,render:m=>h('div',{key:m.id},card(m.name,m.status,null,m.status==='未读'&&btn('标为已读',()=>update(d=>{d.messages.find(r=>r.id===m.id).status='已读'}),{type:'secondary'})))}));
    else if(page==='profile')body=h(React.Fragment,null,heading('我的'),card(data.profile.name,'已绑定',row('绑定手机号','138****0011'),btn('编辑个人资料',()=>go('edit-profile'),{type:'secondary'})),btn('消息通知',()=>go('messages'),{type:'secondary'}),h('div',{className:'stack'},btn('协议与隐私说明',()=>go('legal'),{type:'text'}),btn('退出登录',()=>{update(d=>{d.logged=false});setAgree(false);go('home')},{type:'outline'})));
    else if(page==='edit-profile')body=h(React.Fragment,null,heading('个人资料'),field('姓名',h(Input,{value:name,onChange:setName})),field('性别',h(Select,{value:sex,onChange:setSex,options:['未填写','男','女']})),field('绑定手机号（不可修改）',h(Input,{value:data.profile.phone,disabled:true})),error&&note(error,'error'),btn('保存资料',()=>{if(!name.trim()){setError('姓名不能为空');return}update(d=>{d.profile.name=name.trim();d.profile.sex=sex});go('profile')}));
    else body=h(React.Fragment,null,heading('未找到页面'),btn('返回首页',()=>go('home')));
    return h(Shell,{title:'齿慧通',route,go,nav,back:['benefit','credential','clinics','clinic','booking'].includes(page)?'benefits':['appointment','reschedule'].includes(page)?'appointments':'home'},body);
  }
  window.MINI={role:'customer',routes:['home','benefits','benefit/B1','credential/B2','activate','clinics/B2','clinic/B2/M1','booking/B2/M1','appointments','appointment/A1','reschedule/A1','feedback/A1','feedback/OD72','feedback/ODABS','messages','profile','edit-profile','legal']};
  ReactDOM.createRoot(document.getElementById('root')).render(h(arco.ConfigProvider,null,h(App)));
})();
