(function(){
  'use strict';
  const C=window.CHT,{h,A}=C,base='/api/v1/';
  Object.assign(C.names,{customer_number:'平台客户编号',units:'关联权益份数',completion_source:'完成方式',cancellation_reason:'取消原因',reserved:'权益仍占用',restoration_pending:'待客户申请恢复',clinic_settled:'门诊已结算',settlement_status:'门诊结算状态',redeemed_at:'核销时间',reversed_at:'撤销时间',settled_at:'结算时间',resource_cents:'资源方分配',channel_cents:'渠道方分配',platform_cents:'平台剩余收益',proposed_at:'申请改期时间',previous_at:'原预约时间',initiated_by:'发起方',agreed:'已协商一致',close_reason:'关闭原因',closed_at:'关闭时间'});
  Object.assign(C.labels,{system_timeout:'系统超时完成（未核销）',redeemed:'已核销完成',redemption:'核销完成',system:'系统自动完成（未核销）',automatic:'系统自动完成（未核销）',reversed:'已撤销核销',conflict:'异常搁置',closed:'已关闭',customer:'客户',overdue:'过期预约',supplement:'待补核销'});
  function Actions({row:r}){
    if(C.role!=='clinic')return null;
    const path=base+'appointments/'+r.id;
    const confirm=()=>C.form({title:'确认预约 · '+r.customer_name,fields:[{name:'scheduled_at',label:'确认预约日期与时间',type:'date',time:true}],initial:{scheduled_at:r.requested_at},hint:'请填写已与客户确定的时间，不能超过关联权益到期日期。',submitText:'确认预约',onSubmit:(v,key)=>C.api(path+'/confirm','POST',{version:r.version,scheduled_at:C.iso(v.scheduled_at)},key)});
    const reschedule=()=>C.form({title:'修改预约时间',fields:[{name:'proposed_at',label:'新预约日期与时间',type:'date',time:true},{name:'agreed',label:'是否已与客户协商一致',type:'select',options:[{value:true,label:'已协商一致'}]}],initial:{proposed_at:r.scheduled_at||r.requested_at},hint:'门诊操作改期前必须与客户协商一致。新日期仍不得超过权益有效期。',onSubmit:(v,key)=>C.api(path+'/reschedule','POST',{version:r.version,...v,proposed_at:C.iso(v.proposed_at)},key)});
    return h(A.Space,{wrap:true,className:'detail-actions'},r.status==='pending'&&h(A.Button,{type:'primary',onClick:confirm},'确认预约'),['pending','success'].includes(r.status)&&h(A.Button,{onClick:()=>C.action('取消预约：无法接诊',path+'/cancel',r.version,{},[C.Reason],'仅在确实无法接诊时取消。取消记录及关联权益按当前预约状态处理。')},'无法接诊'),r.status==='success'&&h(A.Button,{onClick:reschedule},'协商改期'),r.status==='success'&&r.scheduled_at&&new Date(r.scheduled_at)<new Date()&&h(A.Button,{onClick:()=>C.action('记录患者未到',path+'/report-absent',r.version,{confirmed:true},[],'预约将取消，但权益不释放。客户需要在小程序申请未到诊，才能恢复关联权益。')},'患者未到'),['success','completed'].includes(r.status)&&r.reserved&&!r.restoration_pending&&!r.redemption_id&&h(A.Button,{type:'primary',onClick:()=>C.open('redeem',{appointment:r})},r.status==='completed'?'补充核销':'扫码核销'));
  }
  C.pages.appointments=function(){
    const [range,setRange]=React.useState([]),[settled,setSettled]=React.useState('');
    const params={date_from:range?.[0],date_to:range?.[1],settled};
    const toolbar=h(A.Space,{wrap:true},h(A.DatePicker.RangePicker,{value:range,onChange:setRange,placeholder:['预约开始日期','预约结束日期']}),h(A.Select,{value:settled,onChange:setSettled,style:{width:170},options:[{value:'',label:'全部结算状态'},{value:'true',label:'门诊已结算'},{value:'false',label:'门诊尚未结算'}]}),C.role==='clinic'&&h(A.Button,{type:'primary',onClick:()=>C.open('redeem',{})},'扫码核销'));
    return h(C.Panel,{title:'预约记录'},h(C.List,{key:C.query(params),path:base+'appointments',params,toolbar,exportPath:base+'appointments/export.xlsx',exportName:'预约明细.xlsx',statusLabels:{pending:'待确认',success:'预约成功'},columns:['customer_name','phone','internal_name','clinic_name','requested_at','scheduled_at','status','settlement_status'].map(k=>C.column(k)),actions:r=>C.button('详情',()=>C.open('appointment',{id:r.id}))}));
  };
  C.dialogs.appointment=function({id,onClose}){const q=C.useQuery(base+'appointments/'+id),r=q.data;return h(C.Drawer,{title:'预约详情',onClose},h(C.Error,{error:q.error,retry:q.reload}),h(A.Spin,{loading:q.loading,style:{width:'100%'}},r&&h('div',null,r.status==='completed'&&!r.redemption_id&&h(A.Alert,{type:'warning',content:'此预约已由系统按超时规则处理，但尚未核销，不产生获客费。权益恢复需客户在小程序申请。'}),r.status==='cancelled'&&r.reserved&&h(A.Alert,{type:'warning',content:'预约已取消，关联权益仍占用；等待客户提交未到诊申请后恢复。'}),h(Actions,{row:r}),h(A.Tabs,{defaultActiveTab:'info'},h(A.Tabs.TabPane,{key:'info',title:'预约资料'},h(C.Facts,{data:r,fields:['id','customer_number','customer_name','phone','internal_name','source_name','clinic_name','units','requested_at','scheduled_at','status','completion_source','cancellation_reason','reserved','restoration_pending','settlement_status','settled_at']})),h(A.Tabs.TabPane,{key:'reschedules',title:'改期记录'},h(A.Table,{rowKey:'id',data:r.reschedules,pagination:false,scroll:{x:800},columns:['previous_at','proposed_at','initiated_by','status','reason'].map(k=>C.column(k)).concat([{title:'操作',width:120,render:(_,v)=>C.button('详情',()=>C.open('reschedule',{row:v}))}])})),h(A.Tabs.TabPane,{key:'redemptions',title:'核销与费用'},h(A.Table,{rowKey:'id',data:r.redemptions,pagination:false,scroll:{x:950},columns:['redeemed_at','status','units','fee_cents','resource_cents','channel_cents','platform_cents','clinic_settled'].filter(k=>r.redemptions.some(v=>v[k]!==undefined)).map(k=>C.column(k)).concat([{title:'操作',width:140,render:(_,v)=>h(A.Space,null,C.button('核销详情',()=>C.open('transaction',{row:v})),C.role==='clinic'&&v.status==='active'&&!v.clinic_settled&&C.button('撤销核销',()=>C.action('撤销错误核销',base+'redemptions/'+v.id+'/reverse',v.version,{},[C.Reason],'已结算交易不能撤销；未结算交易会从有效账单明细移除。系统完成后的补核销撤销，权益需客户申请恢复。')))}])})),h(A.Tabs.TabPane,{key:'logs',title:'操作记录'},h(C.Logs,{type:'appointment',id}))))));};
  C.dialogs.reschedule=({row:r,onClose})=>h(C.Drawer,{title:'客户改期申请',onClose,width:760},h(C.Facts,{data:r,fields:['previous_at','proposed_at','initiated_by','agreed','status','reason']}),C.role==='clinic'&&r.status==='pending'&&h(A.Button,{type:'primary',style:{marginTop:20},onClick:()=>C.action('确认客户改期申请',base+'reschedules/'+r.id+'/review',r.version,{approved:true},C.reviewFields,'审核通过后新时间生效；退回保持原确认时间，系统校验权益有效期。')},'审核改期'));
  C.dialogs.transaction=({row,onClose})=>h(C.Drawer,{title:'核销交易详情',onClose,width:760},h(C.Facts,{data:row}),row.allocation_snapshot&&h(C.Panel,{title:'核销时锁定的费用'},h(C.Facts,{data:row.allocation_snapshot})));
  C.pages.overdue=()=>h(C.Panel,{title:'过期预约待办'},h(A.Alert,{type:'warning',content:'24小时未反馈生成待办，72小时系统完成并关闭待办但不收费、不释放权益。报未到需客户申请恢复；已到诊需补核销。'}),h(C.List,{path:base+'fulfillment-tasks',columns:[{title:'客户',width:150,render:(_,r)=>r.appointment.customer_name},{title:'预约时间',width:180,render:(_,r)=>C.text('scheduled_at',r.appointment.scheduled_at)},C.column('kind','待办类型'),C.column('status'),C.column('created_at'),C.column('close_reason')],actions:r=>C.button('处理预约',()=>C.open('appointment',{id:r.appointment.id}))}));
  C.dialogs.redeem=function({appointment,onClose}){
    const [credential,setCredential]=React.useState(''),[rows,setRows]=React.useState([]),[selected,setSelected]=React.useState(appointment||null),[quote,setQuote]=React.useState(null),[confirmed,setConfirmed]=React.useState(false),[busy,setBusy]=React.useState(false),[error,setError]=React.useState(null);
    const key=React.useRef(crypto.randomUUID());
    async function act(fn){setBusy(true);setError(null);try{await fn();}catch(e){setError(e);}finally{setBusy(false);}}
    function scan(){act(async()=>{const result=await C.api(base+'redemptions/scan','POST',{credential});setRows(result.results);if(appointment&&!result.results.some(r=>r.id===appointment.id))throw new Error('二维码与当前预约不一致');setSelected(appointment||result.results[0]);setQuote(null);setConfirmed(false);});}
    function prepare(){act(async()=>{setQuote(await C.api(base+'redemptions/quote','POST',{appointment_id:selected.id,credential}));key.current=crypto.randomUUID();setConfirmed(false);});}
    function redeem(){act(async()=>{await C.api(base+'redemptions','POST',{appointment_id:selected.id,credential,version:quote.version,confirmed,quote:quote.quote},key.current);C.refresh();A.Message.success('核销已完成，费用已记账');onClose();});}
    return h(C.Drawer,{title:'扫码核销 · 核对服务与费用',onClose,width:760},h(C.Error,{error}),h(A.Steps,{current:quote?3:selected&&rows.length?2:1,size:'small'},h(A.Steps.Step,{title:'扫描固定权益码'}),h(A.Steps.Step,{title:'核对预约与费用'}),h(A.Steps.Step,{title:'确认完成服务'})),h(C.Panel,{title:'二维码内容'},h(A.Alert,{type:'info',content:'使用扫码枪扫描客户的固定权益二维码，或粘贴完整二维码内容。不能凭客户手机号直接核销。'}),h(A.Input.Password,{value:credential,onChange:v=>{setCredential(v);setQuote(null);setRows([]);setConfirmed(false);},onPressEnter:scan,placeholder:'请扫描 / 粘贴权益二维码','aria-label':'权益二维码内容',style:{marginTop:16}}),h(A.Button,{onClick:scan,loading:busy,style:{marginTop:12}},'读取预约')),rows.length>0&&h(C.Panel,{title:'关联预约'},!appointment&&h(A.Select,{value:selected?.id,onChange:id=>{setSelected(rows.find(r=>r.id===id));setQuote(null);},options:rows.map(r=>({value:r.id,label:r.customer_name+' · '+C.text('scheduled_at',r.scheduled_at)})),style:{width:'100%'}}),selected&&h(C.Facts,{data:selected,fields:['customer_name','phone','internal_name','scheduled_at','units','status']}),h(A.Button,{onClick:prepare,loading:busy,style:{marginTop:16}},'核对核销费用')),quote&&h(C.Panel,{title:'本次核销确认'},h(C.Facts,{data:quote,fields:['units','fee_cents']}),h(A.Alert,{type:'warning',content:'本次核销后产生获客费并计入门诊账单。报价5分钟内有效，条款或预约变化须重新核对。'}),h(A.Checkbox,{checked:confirmed,onChange:setConfirmed,style:{marginTop:16}},'客户已完成本次服务，确认核销'),h(A.Button,{type:'primary',disabled:!confirmed,loading:busy,onClick:redeem,style:{display:'block',marginTop:16}},'确认核销')));
  };
})();
