(function () {
  'use strict';
  const C = window.CHT, {h, A} = C, base = '/api/v1/';
  Object.assign(C.names, {payment_mode:'付款方式', subject_name:'签约主体', debtor_name:'付款责任主体', content_status:'内容审核', clinic_count:'负责范围内门店数', signed_attachment_ids:'双方完整签署件', error_code:'待核实问题'});
  const mode = v => v === 'instant' ? '核销现付' : '账单后付';
  function subjectForm() {
    C.form({title:'登记签约主体', hint:'填写承担付款责任的法定签约主体全称。连锁总部可覆盖多门店，独立单店只能采用核销现付；品牌名不能代替签约主体。', fields:[{name:'name',label:'法定签约主体全称'}, {name:'kind',label:'合作类型',type:'select',options:C.options({chain:'连锁总部',single:'独立单店'})}, {name:'admin_name',label:'主体管理员姓名'}, {name:'admin_phone',label:'主体管理员手机号'}], initial:{kind:'chain'}, onSubmit:v=>C.api(base+'clinic-cooperations','POST',v)});
  }
  const Stores = C.pages.clinics;
  C.pages.clinics = () => h(A.Tabs,{defaultActiveTab:'stores'},h(A.Tabs.TabPane,{key:'stores',title:'门店管理'},h(Stores)),h(A.Tabs.TabPane,{key:'subjects',title:'签约主体与合同'},h(C.Panel,{title:'签约主体与合同',extra:['platform','channel'].includes(C.role)&&h(A.Button,{type:'primary',onClick:subjectForm},'新增签约主体')},h(A.Alert,{type:'info',content:'先登记签约主体，再在新增门店时选择主体。合同按主体签署，门店资料及推广产品逐店审核上线。未选择主体的新门店默认独立单店。'}),h(C.List,{path:base+'clinic-cooperations',search:true,columns:[C.column('name','签约主体'),{title:'合作类型',render:(_,r)=>r.kind==='chain'?'连锁总部':'独立单店'},{title:'付款方式',render:(_,r)=>mode(r.payment_mode)},C.column('clinic_count'),C.column('status')],actions:r=>[C.button('详情',()=>C.open('cooperationSubject',{id:r.id}))]}))));
  C.Agreements = function({id}) {
    const q=C.useChoices(base+'clinic-cooperations/'+id);
    return h(C.Panel,{title:'双方合同与覆盖门店',extra:q.data?.can_manage&&h(A.Button,{type:'primary',onClick:()=>C.open('agreementForm',{subject:q.data})},'登记合同 / 续签')},h(C.Error,{error:q.error,retry:q.reload}),h(C.List,{path:base+'clinic-cooperations/'+id+'/agreements',columns:[C.column('number','合同编号'),C.column('revision','版本'),C.column('status'),C.column('ends_at','到期时间'),{title:'付款方式',render:(_,r)=>mode(r.payment_mode)}],actions:r=>[C.button('详情',()=>C.open('agreement',{id:r.id}))]}));
  };
  C.dialogs.cooperationSubject=function({id,onClose}) {
    const q=C.useChoices(base+'clinic-cooperations/'+id),r=q.data;
    return h(C.Drawer,{title:'签约主体管理',onClose},h(C.Error,{error:q.error,retry:q.reload}),r&&h(React.Fragment,null,h(C.Facts,{data:r,fields:['name','clinic_count','status']}),h(A.Tabs,null,h(A.Tabs.TabPane,{key:'agreement',title:'双方合同'},h(C.Agreements,{id})),h(A.Tabs.TabPane,{key:'stores',title:'覆盖门店'},h(C.List,{path:base+'clinics?cooperation_id='+id,columns:[{title:'门店',render:(_,x)=>x.profile.name},C.column('review_status'),C.column('service_status')],actions:x=>[C.button('门店详情',()=>C.open('clinic',{id:x.id}))]})),r.can_manage&&h(A.Tabs.TabPane,{key:'logs',title:'操作记录'},h(C.Logs,{type:'cliniccooperation',id})))));
  };
  C.dialogs.agreementForm=function({subject,row,onClose}) {
    const stores=C.useChoices(base+'clinics?cooperation_id='+subject.id+'&page_size=100'), products=C.useChoices(base+'products?page_size=100');
    const multi=(name,label,items)=>({name,label,render:()=>h(A.Select,{mode:'multiple',options:items})});
    return h(C.FormDialog,{title:row?'修改合同草稿':'登记双方合同 / 续签',onClose,hint:'须上传门诊已签署的全部页面。平台收到原件、签署并上传双方完整签署件后才能审核生效；寄回门诊不阻塞上线。后付账单的付款责任属于签约主体。',initial:row?{...row,clinic_ids:row.coverage.map(x=>x.id),contact_name:row.contact.name,contact_phone:row.contact.phone}:{settlement_cycle:subject.kind==='chain'?'monthly':''},fields:[{name:'number',label:'合同编号'},{name:'starts_at',label:'生效日期',type:'date',time:true},{name:'ends_at',label:'到期日期',type:'date',time:true},{name:'contact_name',label:'业务联系人'},{name:'contact_phone',label:'联系人手机号'},...(subject.kind==='chain'?[{name:'settlement_cycle',label:'结算周期',type:'select',options:C.options({weekly:'周结',monthly:'月结'})}]:[]),multi('clinic_ids','覆盖门店',(stores.data?.results||[]).map(x=>({value:x.id,label:x.profile.name}))),multi('product_ids','合同推广产品',(products.data?.results||[]).map(x=>({value:x.id,label:x.internal_name}))),{name:'attachment_ids',label:'门诊签署的全部合同页',type:'files',purpose:'contract'}],onSubmit:v=>{const data={number:v.number,starts_at:new Date(v.starts_at).toISOString(),ends_at:new Date(v.ends_at).toISOString(),contact:{name:v.contact_name,phone:v.contact_phone},clinic_ids:v.clinic_ids,product_ids:v.product_ids,attachment_ids:v.attachment_ids,payment_mode:subject.kind==='chain'?'postpaid':'instant',settlement_cycle:subject.kind==='chain'?v.settlement_cycle:''};return row?C.api(base+'clinic-agreements/'+row.id,'POST',{version:row.version,data}):C.api(base+'clinic-cooperations/'+subject.id+'/agreements','POST',data);}});
  };
  function paper(r) {
    const fields=r.status==='approved'?[{name:'return_carrier',label:'寄回快递公司'},{name:'return_tracking',label:'寄回单号'},{name:'returned_at',label:'寄回时间',type:'date',time:true}]:[{name:'outbound_carrier',label:'寄往平台快递公司',optional:true},{name:'outbound_tracking',label:'寄往平台单号',optional:true},{name:'recipient',label:'门诊收件人',optional:true},{name:'recipient_phone',label:'收件电话',optional:true},{name:'return_address',label:'寄回地址',optional:true},...(C.role==='platform'?[{name:'received_at',label:'平台收到原件时间',type:'date',time:true},{name:'platform_signed_at',label:'平台签署时间',type:'date',time:true},{name:'signed_attachment_ids',label:'双方签署完整合同',type:'files',purpose:'contract'}]:[])];
    C.form({title:'纸质合同收签与寄回',fields,initial:{...r.paper,signed_attachment_ids:r.signed_attachment_ids},onSubmit:v=>{const data={};for(const f of fields){if(v[f.name])data[f.name]=f.type==='date'?new Date(v[f.name]).toISOString():v[f.name];}return C.api(base+'clinic-agreements/'+r.id+'/paper','POST',{version:r.version,data});}});
  }
  C.dialogs.agreement=function({id,onClose}) {
    const q=C.useChoices(base+'clinic-agreements/'+id),r=q.data;
    return h(C.Drawer,{title:'双方合同详情',onClose},h(C.Error,{error:q.error,retry:q.reload}),r&&h(React.Fragment,null,h(A.Alert,{type:'info',content:r.scope_notice||'内容审核可与邮寄并行；最终审核必须具备原件收件记录及双方完整签署附件。'}),h(A.Space,{wrap:true,className:'detail-actions'},r.can_manage&&r.status==='draft'&&C.button('修改草稿',()=>C.open('agreementForm',{subject:{id:r.cooperation_id,kind:r.payment_mode==='instant'?'single':'chain'},row:r})),r.can_manage&&r.status==='draft'&&C.button('提交审核',()=>C.action('提交审核',base+'clinic-agreements/'+id+'/submit',r.version,{},[])),r.can_manage&&['draft','pending','approved'].includes(r.status)&&(r.status!=='approved'||C.role==='platform')&&C.button('原件收签 / 寄回',()=>paper(r)),C.role==='platform'&&r.status==='pending'&&C.button('审核合同',()=>C.action('审核双方合同',base+'clinic-agreements/'+id+'/review',r.version,{approved:true,final:false},[{name:'approved',label:'审核通过',type:'boolean'},{name:'final',label:'完成最终审核并生效',type:'boolean'},C.Reason])),C.role==='platform'&&r.status==='approved'&&C.button('终止合同',()=>C.action('终止双方合同',base+'clinic-agreements/'+id+'/terminate',r.version,{},[C.Reason]))),h(C.Facts,{data:r,fields:['subject_name','number','revision','status','starts_at','ends_at','settlement_cycle','due_at','reason']}),h(A.Typography.Paragraph,null,'付款方式：'+mode(r.payment_mode)),h(C.Panel,{title:'覆盖门店'},h(A.Space,{wrap:true},r.coverage.map(x=>h(A.Tag,{key:x.id},x.name)))),h(C.Panel,{title:'门诊签署件'},h(C.Attachments,{ids:r.attachment_ids})),h(C.Panel,{title:'双方最终签署件'},h(C.Attachments,{ids:r.signed_attachment_ids})),r.can_manage&&h(C.Panel,{title:'原件流转记录'},h(C.Facts,{data:r.paper})),r.can_manage&&h(C.Logs,{type:'clinicagreement',id})));
  };
  C.pages.instantOrders=()=>h(C.Panel,{title:'核销现付订单'},h(A.Alert,{type:'info',content:'已付款才完成核销。结果未决时先查单；已收款待核销可重试完成，不重新收费。本期不提供错误核销退款。'}),h(C.List,{path:base+'instant-orders',columns:[C.column('clinic_name'),C.column('internal_name'),C.column('amount_cents','获客费'),C.column('status'),C.column('paid_at'),C.column('error_code')],actions:r=>[C.button('详情 / 支付处理',()=>C.open('instant',{id:r.id}))]}));
  C.dialogs.instant=function({id,onClose}) {
    const q=C.useChoices(base+'instant-orders/'+id),r=q.data;
    return h(C.Drawer,{title:'核销现付订单',onClose,width:760},h(C.Error,{error:q.error,retry:q.reload}),r&&h(React.Fragment,null,h(C.Facts,{data:r,fields:['clinic_name','debtor_name','internal_name','amount_cents','status','paid_at','error_code']}),h(A.Alert,{type:'warning',content:'付款责任为合同签约主体，实际付款人可为门诊前台。已核销现付订单本期不支持撤销或退款。'}),r.status==='paid'&&['platform','clinic'].includes(C.role)&&C.button('重试完成核销',()=>C.form({title:'重试完成核销',fields:[],onSubmit:()=>C.api(base+'instant-orders/'+id,'POST',{confirmed:true})})),...(r.payments||[]).map(p=>h(C.Panel,{key:p.id,title:'支付记录'},p.simulated&&h(A.Alert,{type:'warning',content:'模拟验收交易，不发生真实资金往来。'}),h(C.Facts,{data:p,fields:['number','amount_cents','status','error_code']}),p.payment_parameters?.code_url&&!p.simulated&&h('div',null,h(A.Typography.Paragraph,{copyable:true},p.payment_parameters.code_url),h(A.Alert,{type:'info',content:'请在支持微信收银的终端使用此支付链接；付款后点击查询确认。'})),['platform','clinic'].includes(C.role)&&['query','close','retry'].map(action=>C.button({query:'查询付款结果',close:'查单并关闭未付订单',retry:'重试生成支付信息'}[action],()=>C.form({title:'核对支付结果',fields:[],onSubmit:()=>C.api(base+'payments/'+p.id+'/'+action,'POST',{confirmed:true})}))))),h(C.Logs,{type:'instantredemptionorder',id})));
  };
})();
