(function(){
  'use strict';
  const C=window.CHT,{h,A}=C,base='/api/v1/';
  Object.assign(C.names,{mode:'销售方式',entry:'录入方式',unit_price_cents:'单卡采购价',units_per_card:'每卡权益份数',serial:'卡号',activated_at:'激活时间',frozen:'已冻结',resource_customer_no:'资源方客户编号',gender:'性别',age:'年龄',occupation:'职业',recipient:'收件人',carrier:'快递公司',tracking_number:'快递单号',refunded_at:'退款时间',issue_failure_code:'开卡异常'});
  Object.assign(C.labels,{quantity:'按数量开卡',single:'单个客户',excel:'Excel批量',male:'男',female:'女'});
  C.pages.sales=()=>h(C.Panel,{title:'推广产品销售',extra:C.role==='resource'&&h(A.Button,{type:'primary',onClick:()=>C.open('saleWizard',{})},'创建销售订单')},h(C.List,{path:base+'sales-orders',columns:[{title:'推广产品',width:220,render:(_,r)=>r.product_snapshot.internal_name},C.column('mode'),C.column('quantity','开卡张数'),C.column('unit_price_cents'),C.column('total_cents','采购总额'),C.column('source_name'),C.column('status')],actions:r=>C.button('订单详情',()=>C.open('sale',{id:r.id}))}));
  function SalesActions({row:r}){
    const path=base+'sales-orders/'+r.id;
    const exportCards=()=>A.Modal.confirm({title:'下载实体卡制卡资料',content:'文件包含未激活卡的激活凭证，请安全保管，不要分享给无关人员。',onOk:async()=>{const blob=await C.request(path+'/cards/export',{method:'POST',body:{confirmed:true},binary:true});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='实体卡制卡资料.xlsx';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}});
    return h(A.Space,{wrap:true,className:'detail-actions'},C.role==='resource'&&['pending_payment','payment_review'].includes(r.status)&&h(A.Button,{type:'primary',onClick:()=>C.receiptForm('上传采购付款凭证',path+'/receipts',{...r,remaining_cents:r.total_cents-r.received_cents})},'上传付款凭证'),C.role==='platform'&&r.status==='pending_approval'&&h(A.Button,{type:'primary',onClick:()=>C.action('审核开卡销售',path+'/review',r.version,{approved:true,validity_days:r.validity_days},[...C.reviewFields,{name:'validity_days',type:'number',min:1,max:36500}],'确认当前名单、产品、数量、采购款及有效期；领取 / 激活后开始计算权益有效期。')},'审核开卡'),C.role==='platform'&&['cancel_pending','stop_pending'].includes(r.status)&&h(A.Button,{type:'primary',onClick:()=>C.action('审核取消 / 停止申请',path+'/stop-review',r.version,{approved:true},C.reviewFields,'整单取消要求全部卡未激活；停止仅失效尚未领取部分，不恢复已领取权益。')},'审核申请'),C.role==='resource'&&!['cancel_pending','stop_pending','cancelled','stopped'].includes(r.status)&&h(A.Button,{onClick:()=>C.action('申请取消 / 停止销售',path+'/stop',r.version,{action:'cancel'},[{name:'action',label:'申请类型',type:'select',options:C.options({cancel:'取消整单（所有卡均未激活）',stop:'停止剩余未领取权益'})},C.Reason],'提交后由平台审核。已激活实体卡不支持转让；争议请联系平台处理。')},'取消 / 停止申请'),C.role==='platform'&&r.status==='cancelled'&&r.received_cents>0&&!Object.keys(r.refund||{}).length&&h(A.Button,{onClick:()=>C.form({title:'登记线下采购退款',fields:[{name:'amount',label:'退款金额（元）',type:'number',min:.01,precision:2},{name:'refunded_at',type:'date',time:true},{name:'reference',label:'退款流水号'},{name:'attachment_ids',label:'退款凭证',type:'files',purpose:'payment'},C.Reason],initial:{amount:r.received_cents/100},hint:'请先在线下完成退款，本操作只登记金额和凭证，不发起资金转账。',onSubmit:(v,key)=>{const {amount,...data}=v;return C.api(path+'/refund','POST',{...data,amount_cents:Math.round(amount*100),refunded_at:C.iso(data.refunded_at),version:r.version},key);}})},'登记退款'),C.role==='platform'&&r.mode==='physical'&&r.status==='issued'&&h(A.Button,{onClick:()=>C.action('登记实体卡寄送',path+'/shipment',r.version,{},[{name:'recipient'},{name:'phone',label:'收件手机号'},{name:'address',label:'收件地址'},{name:'carrier'},{name:'tracking_number'}],'实体卡线下制作及寄送，线上保存寄送记录。')},'登记寄送'),r.mode==='physical'&&r.status==='issued'&&h(A.Button,{onClick:exportCards},'下载制卡 Excel'));
  }
  C.dialogs.sale=function({id,onClose}){const q=C.useChoices(base+'sales-orders/'+id),r=q.data;React.useEffect(()=>{if(!['issuing'].includes(r?.status))return;const id=setInterval(q.reload,3000);return()=>clearInterval(id);},[r?.status]);return h(C.Drawer,{title:'推广产品销售订单',onClose},h(C.Error,{error:q.error,retry:q.reload}),h(A.Spin,{loading:q.loading,style:{width:'100%'}},r&&h('div',null,h(A.Alert,{type:'info',content:r.product_snapshot.internal_name+' · '+C.label(r.mode)+' · '+r.quantity+'张 · 采购总额 '+C.money(r.total_cents)+'。采购款由资源方向平台支付。'}),h(SalesActions,{row:r}),h(A.Tabs,{defaultActiveTab:'info'},h(A.Tabs.TabPane,{key:'info',title:'订单资料'},h(C.Facts,{data:r,fields:['id','mode','entry','quantity','units_per_card','unit_price_cents','total_cents','received_cents','source_name','validity_days','status','reason','issue_failure_code']}),r.number_range&&h(C.Panel,{title:'本批卡号段'},r.number_range.first+' ～ '+r.number_range.last),h(C.Panel,{title:'推广产品快照'},h(C.Facts,{data:r.product_snapshot})),Object.keys(r.shipment||{}).length>0&&h(C.Panel,{title:'寄送记录'},h(C.Facts,{data:r.shipment})),Object.keys(r.refund||{}).length>0&&h(C.Panel,{title:'退款记录'},h(C.Facts,{data:r.refund}),h(C.Attachments,{ids:r.refund.attachment_ids||[]}))),r.mode==='named'&&h(A.Tabs.TabPane,{key:'customers',title:'客户名单'},h(C.List,{path:base+'sales-orders/'+id+'/rows',columns:[{title:'原行号',dataIndex:'row_number',width:100},...['name','phone','quantity','resource_customer_no','gender','age','occupation'].map(key=>({title:C.names[key]||key,width:150,render:(_,v)=>C.text(key,v.normalized[key])}))]})),h(A.Tabs.TabPane,{key:'cards',title:'卡片明细'},h(C.List,{path:base+'sales-orders/'+id+'/cards',columns:['serial','status','frozen','activated_at'].map(k=>C.column(k)),actions:C.role==='platform'?v=>C.button(v.frozen?'解除冻结':'冻结',()=>C.action(v.frozen?'解除卡片冻结':'冻结卡片',base+'cards/'+v.id+'/freeze',null,{frozen:!v.frozen},[C.Reason],'冻结后不得继续激活或使用，记录争议处理原因。')):null})),h(A.Tabs.TabPane,{key:'receipts',title:'采购收款凭证'},h(C.List,{path:base+'sales-orders/'+id+'/receipts',columns:['amount_cents','paid_at','payer','reference','status'].map(k=>C.column(k)),actions:v=>C.button('凭证详情',()=>C.open('purchaseReceipt',{row:v}))})),r.import_batch_id&&h(A.Tabs.TabPane,{key:'import',title:'Excel导入依据'},h(C.ImportReceipt,{id:r.import_batch_id})),h(A.Tabs.TabPane,{key:'logs',title:'操作记录'},h(C.Logs,{type:'salesorder',id}))))));};
  C.dialogs.purchaseReceipt=({row:r,onClose})=>h(C.Drawer,{title:'采购付款凭证',onClose,width:760},h(C.Facts,{data:r,fields:['id','amount_cents','paid_at','payer','reference','status','reason']}),h(C.Panel,{title:'全部付款凭证'},h(C.Attachments,{ids:r.attachment_ids})),C.role==='platform'&&r.status==='pending'&&h(A.Button,{type:'primary',style:{marginTop:20},onClick:()=>C.action('确认采购款到账',base+'purchase-receipts/'+r.id+'/review',r.version,{approved:true},C.reviewFields,'核实实际到账记录后审核。只有足额到账，非零采购订单才能进入开卡审核。')},'审核收款'));
  C.dialogs.saleWizard=function({onClose}){
    const [step,setStep]=React.useState(1),[draft,setDraft]=React.useState({selection:'physical'});
    const org=C.actor.organization_id,cooperation=C.useChoices(base+'organizations/'+org+'/cooperation'),brands=C.useChoices(base+'organizations/'+org+'/source-brands?status=active&page_size=100');
    const products=C.useChoices(cooperation.data?.products_endpoint?cooperation.data.products_endpoint+'?status=active&page_size=100':null);
    const members=C.useChoices(C.actor.role==='admin'?base+'organizations/'+org+'/members?status=active&page_size=100':null);
    let fields;
    if(step===1)fields=[{name:'selection',label:'销售方式',type:'select',options:C.options({physical:'不记名实体卡',named_single:'记名非实体卡 · 单卡销售',named_excel:'记名非实体卡 · 批量Excel'})}];
    else if(step===2)fields=draft.selection==='physical'?[{name:'quantity',label:'开卡张数',type:'number',min:1,max:100000}]:draft.selection==='named_single'?[{name:'name',label:'客户姓名'},{name:'phone',label:'客户手机号'},{name:'quantity',label:'开卡张数',type:'number',min:1,max:100000},{name:'resource_customer_no',optional:true},{name:'gender',type:'select',options:C.options({male:'男',female:'女',unknown:'未知'}),optional:true},{name:'age',type:'number',max:150,optional:true},{name:'occupation',optional:true}]:[{name:'import',label:'Excel列适配与确认',render:()=>h(C.ImportEditor)}];
    else fields=[{name:'product_id',label:'推广产品',type:'select',options:(products.data?.results||[]).map(p=>({value:p.product_id,label:p.product.internal_name}))},{name:'source_brand_id',label:'对客户展示的权益来源',type:'select',options:(brands.data?.results||[]).map(b=>({value:b.id,label:b.name}))},{name:'units_per_card',label:'每张卡绑定权益份数',type:'number',min:1,max:10000},{name:'price',label:'单卡采购价（元，资源方向平台支付）',type:'number',precision:2,min:0},{name:'responsible_id',label:'订单负责业务员',type:'select',disabled:C.actor.role!=='admin',options:members.data?.results.map(m=>({value:m.id,label:m.name}))||[{value:C.actor.id,label:'本人'}]}];
    const total=draft.quantity||draft.import?.total_cards||0;
    return h(C.FormDialog,{title:'创建推广产品销售订单',onClose,width:900,fields,initial:{...draft,units_per_card:1,price:0,responsible_id:C.actor.id},submitText:step===3?'提交开卡订单':'下一步',hint:h('div',null,h(A.Steps,{current:step,size:'small'},h(A.Steps.Step,{title:'选择销售方式'}),h(A.Steps.Step,{title:'客户与开卡数量'}),h(A.Steps.Step,{title:'产品与采购价'})),h('p',null,step===2?'平台客户编号自动生成；资源方客户编号仅保留，不作为身份关联。客户可选资料仅补空，不覆盖已有值。':step===3?'开卡数量 '+total+' 张；零元直接进入审核，非零需确认采购款到账后才能审核开卡。':'实体卡不需要上传Excel，系统自动生成不重复号段。'),step>1&&h(A.Button,{type:'text',onClick:()=>setStep(v=>v-1)},'上一步'),h(C.Error,{error:cooperation.error||products.error||brands.error})),onSubmit:async(v,key)=>{const data={...draft,...v};setDraft(data);if(step<3){if(step===2&&draft.selection==='named_excel'&&v.import?.status!=='confirmed')throw new Error('请先完成列校验并确认导入');setStep(step+1);return false;}const payload={mode:data.selection==='physical'?'physical':'named',entry:data.selection==='physical'?'quantity':data.selection==='named_single'?'single':'excel',product_id:data.product_id,source_brand_id:data.source_brand_id,unit_price_cents:Math.round(data.price*100),units_per_card:data.units_per_card,responsible_id:data.responsible_id};if(data.selection==='physical')payload.quantity=data.quantity;else if(data.selection==='named_single')payload.rows=[Object.fromEntries(['name','phone','quantity','resource_customer_no','gender','age','occupation'].filter(k=>data[k]!==undefined).map(k=>[k,data[k]]))];else payload.import_batch_id=data.import.id;const result=await C.api(base+'sales-orders','POST',payload,key);C.open('sale',{id:result.id});return result;}});
  };
})();
