(() => {
  const {h,clone,useStore,useRoute,btn,note,field,row,card,heading,validDate,StateList,Shell,confirm,log,today}=Mini;
  const {useState,useEffect}=React,{Input,Select,Checkbox}=arco;
  const OD=PrototypeOverdue;
  const nav=[['home','工作台','⌂'],['appointments','预约','▣'],['scan','核销','▧'],['profile','我的','○']];
  const seed={logged:false,phone:'13800000001',clinic:'明禾口腔',baseDebt:540,
    appointments:[{id:'V1',name:'客户甲（演示）',phone:'13800000011',source:'安和保险客户福利',status:'成功',date:today,time:'10:00',intent:today+' 10:00',expiry:'2027-03-06',fee:60,quantity:1,held:1,used:0,token:'VISIT-001',canRedeem:true},
      {id:'V2',name:'客户乙（演示）',phone:'13800000012',source:'星海银行信用卡礼遇',status:'待确认',date:'2026-09-08',time:'14:00',intent:'2026-09-08 14:00',expiry:'2027-03-06',fee:60,quantity:1,held:1,used:0,token:'VISIT-002',canRedeem:true},
      {id:'V3',name:'客户丙（演示）',phone:'13800000013',source:'安和保险客户福利',status:'成功',date:'2026-09-09',time:'15:00',intent:'2026-09-09 15:00',expiry:'2027-03-06',fee:60,quantity:1,held:1,used:0,token:'VISIT-003',canRedeem:true,change:{date:'2026-09-10',time:'16:00'}},
      {id:'V4',name:'客户丁（演示）',phone:'13800000014',source:'安和保险客户福利',status:'成功',date:'2026-09-06',time:'11:00',intent:'2026-09-06 11:00',expiry:'2027-03-06',fee:60,quantity:1,held:1,used:0,token:'VISIT-004',canRedeem:false,followup:true},
      {id:'V5',name:'客户戊（演示）',phone:'13800000015',source:'安和保险客户福利',status:'完成',date:'2026-09-05',time:'10:00',intent:'2026-09-05 10:00',expiry:'2027-03-06',fee:60,quantity:1,held:0,used:1,token:'VISIT-005',canRedeem:false},
      {id:'V6',name:'客户己（演示）',phone:'13800000016',source:'安和保险客户福利',status:'完成',date:'2026-08-30',time:'10:00',intent:'2026-08-30 10:00',expiry:'2027-03-06',fee:60,quantity:1,held:0,used:1,token:'VISIT-006',canRedeem:false}],
    redemptions:[{id:'R1',appointment:'V5',amount:60,quantity:1,settled:false,status:'已核销',time:'2026-09-05 10:30',operator:'门诊员工（演示）'},
      {id:'R2',appointment:'V6',amount:60,quantity:1,settled:true,status:'已核销',time:'2026-08-30 10:30',operator:'门诊员工（演示）'}],
    reversals:[],messages:[{id:'N1',name:'有1条预约待确认，请在门诊约定的24小时内处理。',status:'未读'},{id:'N2',name:'客户丙申请改期，原预约时间仍有效。',status:'未读'}]};
  function AppointmentForm({appointment,mode,onSubmit}){const [date,setDate]=useState(mode==='change-request'?appointment.change.date:appointment.date),[time,setTime]=useState(mode==='change-request'?appointment.change.time:appointment.time),[agreed,setAgreed]=useState(false),[reason,setReason]=useState(''),[error,setError]=useState('');const cancel=mode==='cancel';return h('section',{className:'card'},note(cancel?'仅在无法接诊时取消，系统释放关联权益并通知客户。':'须先与客户沟通时间。当前有效时间：'+appointment.date+' '+appointment.time),cancel?field('无法接诊原因',h(Input.TextArea,{value:reason,onChange:setReason,placeholder:'请说明无法接诊的具体原因'})):h(React.Fragment,null,field('预约日期',h('input',{type:'date',value:date,min:today,max:appointment.expiry,onChange:e=>setDate(e.target.value)})),field('预约时间',h('input',{type:'time',value:time,onChange:e=>setTime(e.target.value)})),mode==='reschedule'&&h(Checkbox,{checked:agreed,onChange:setAgreed},'已与客户协商一致')),error&&note(error,'error'),btn(cancel?'确认无法接诊':mode==='confirm'?'确认预约时间':mode==='change-request'?'同意本次改期':'确认改期',()=>{const error=cancel?(!reason.trim()?'请填写无法接诊原因':null):validDate(date,time,appointment.expiry)||(mode==='reschedule'&&!agreed?'请确认已与客户协商一致':null);if(error){setError(error);return}onSubmit({date,time,reason,agreed})}));}
  function App(){
    const [data,save]=useStore('chihuitong-clinic-mini-v1',seed,d=>ClinicFinance.migrate(OD.miniMigrate(d,'clinic'))),[route,go]=useRoute(),[identity,setIdentity]=useState('已开通员工'),[agree,setAgree]=useState(false),[error,setError]=useState(''),[code,setCode]=useState(''),[scanned,setScanned]=useState(''),[service,setService]=useState(false),[reason,setReason]=useState(''),[riskScene,setRiskScene]=useState('正常'),[feedback,setFeedback]=useState('');
    useEffect(()=>{setError('');setReason('');setFeedback('')},[route]);
    const [page,id]=route.split('/'),a=data.appointments.find(a=>a.id===id),r=data.redemptions.find(r=>r.id===id);
    const update=fn=>{const next=clone(data);fn(next);save(next)};
    const overdueAction=(id,action)=>{try{const next=clone(data),item=next.appointments.find(a=>a.id===id);OD.act(item,action,'clinic');log(next,'过期预约 '+id+' 已处理，权益仍占用，通知客户（模拟）');save(next);}catch(e){arco.Message.error(e.message)}};
    const overdueTasks=data.appointments.flatMap(a=>(a.overdueTasks||[]).map(t=>({...t,appointment:a.id,name:a.name,date:a.date,time:a.time})));
    const isAdmin=ClinicFinance.admin(data);
    const debt=data.baseDebt+data.redemptions.filter(r=>!r.settled&&r.status==='已核销').reduce((n,r)=>n+r.amount,0);
    
    const blocked=riskScene==='平台人工下线';
    const appointments=data.appointments;
    const clinicSettlement=a=>{const redemption=data.redemptions.find(r=>r.appointment===a.id&&r.status==='已核销');return redemption?(redemption.settled?'已结清':'未结清'):a.completionSource==='系统超时处理'||a.overdueManaged?'未产生费用':a.status==='完成'?'依据待补充':'未产生费用'};
    const viewAppointment=a=>h('div',{key:a.id},card(a.name,a.status,h(React.Fragment,null,row(a.status==='待确认'?'意向时间':'预约时间',a.date+' '+a.time),h('p',{className:'muted'},a.source+' · '+(a.externalName||'舒适洁牙服务')+' · 1份'),row('门诊结算状态',clinicSettlement(a)),a.change&&note('客户改期待确认'),a.overdueManaged&&note(OD.summary(a),'warn')),btn('查看预约',()=>go('appointment/'+a.id),{type:'secondary'})));
    const scanAppointment=data.appointments.find(a=>a.token===scanned);
    const scanError=()=>{if(!scanned)return '';if(scanned==='VISIT-EXPIRED')return '权益已过期，不能核销';if(scanned==='VISIT-OTHER')return '此凭证不属于本门诊预约，无权核销';if(scanned==='VISIT-FROZEN')return '权益已冻结，不能核销';if(!scanAppointment)return '未找到演示预约，请核对凭证';return OD.redeemError(scanAppointment);};
    let body;
    if(!data.logged&&page!=='binding')body=h(React.Fragment,null,heading('门诊工作区','仅供已开通的门诊员工使用'),h('div',{className:'hero'},h('h2',null,'预约处理与权益核销'),h('p',null,'先由门诊后台开通账号并预留手机号，再使用同一手机号绑定。')),field('演示登录身份',h(Select,{value:identity,onChange:setIdentity,options:['已开通员工','已开通管理员','手机号未开通','员工账号已停用']})),note('模拟微信手机号授权，演示员工138****0001。普通客户不会在此自动注册成员工。'),h(Checkbox,{checked:agree,onChange:setAgree},'我已了解演示数据与员工账号绑定说明'),error&&note(error,'error'),h('div',{className:'stack'},btn('员工手机号授权登录（演示）',()=>{if(!agree){setError('请先确认员工账号绑定说明');return}if(!['已开通员工','已开通管理员'].includes(identity)){setError(identity==='手机号未开通'?'该手机号未开通门诊员工，请联系门诊管理员':'员工账号已停用，请联系门诊管理员');return}update(d=>{d.logged=true;d.identity=identity==='已开通管理员'?'管理员':'员工'});go('home')}),btn('查看账号开通与绑定流程',()=>go('binding'),{type:'text'})));
    else if(page==='binding')body=h(React.Fragment,null,heading('员工开通与绑定'),card('1. 后台预先开通',null,h('p',null,'门诊管理员在本门诊后台填写员工姓名和预留手机号。')),card('2. 员工手机号授权',null,h('p',null,'进入门诊专用小程序，使用同一手机号授权；系统检查员工、所属门诊和账号状态。')),card('3. 绑定后进入本门诊',null,h('p',null,'只可处理本门诊业务。账号停用后不能继续操作，不自动切换到客户端身份。')),btn('返回',()=>go('home')));
    else if(['bills','bill','credit','contract'].includes(page)&&!isAdmin)body=h(React.Fragment,null,heading('无权访问'),note('仅门诊管理员可查看合同、账单和付款信息。员工请处理预约相关工作。','error'),btn('返回工作台',()=>go('home')));
    else if(page==='contract')body=h(ClinicFinance.Contract);
    else if(page==='home')body=h(React.Fragment,null,heading(data.clinic,data.identity+' · 今日待办'),riskScene==='逾期待处理'&&isAdmin&&note('账单已逾期，请及时付款；不自动下线，平台按实际情况人工处理。','warn'),blocked&&note('门诊临时下线：'+riskScene+'。不能承接新预约，已有预约继续履约。','warn'),h('div',{className:'count-grid'},h('button',{onClick:()=>go('appointments')},h('b',null,appointments.filter(a=>a.status==='待确认').length),'待确认'),h('button',{onClick:()=>go('appointments')},h('b',null,appointments.filter(a=>a.change).length),'改期待处理'),h('button',{onClick:()=>go('followups')},h('b',null,overdueTasks.filter(t=>t.status!=='已关闭').length),'过期预约待办')),btn('扫码核销权益',()=>{setScanned('');setService(false);go('scan')}),card('优先处理',null,null,h(React.Fragment,null,btn('处理预约',()=>go('appointments'),{type:'secondary'}),btn('过期预约待办',()=>go('followups'),{type:'secondary'}))),isAdmin&&card('合同账单与收款',blocked?'临时下线':'正常',h(React.Fragment,null,row('已核销待结算',debt.toFixed(2)+'元'),row('结算周期','周结'),row('三方合同','平台 / 启明渠道 / 本门诊')),btn('查看账单与收款',()=>go('bills'),{type:'secondary'})));
    else if(page==='appointments')body=h(React.Fragment,null,heading('预约管理','按记录状态处理本门诊预约'),h(StateList,{states:['待确认','成功','完成','取消'],items:appointments,render:viewAppointment}));
    else if(page==='appointment'&&a)body=h(React.Fragment,null,heading(a.name),card('预约信息',a.status,h(React.Fragment,null,row('预约编号',a.id),row('预约手机号',a.phone),row('意向时间',a.intent),row('当前预约',a.date+' '+a.time),row('推广产品',a.externalName||'舒适洁牙服务'),row('门诊结算状态',clinicSettlement(a)),a.overdueManaged&&note(OD.summary(a),'warn'),a.overdueManaged&&btn('过期预约处理',()=>go('feedback/'+a.id),{type:'secondary'}),row('权益来源',a.source),row('权益到期',a.expiry),row('预约占用 / 已用',a.held+' / '+a.used),row('单次获客费',a.fee+'元（核销时记账）'),a.change&&note('改期请求：'+a.change.date+' '+a.change.time+'；原预约仍有效。','warn'),a.feedback&&note('反馈：'+a.feedback),a.reason&&row('取消原因',a.reason)),h(React.Fragment,null,btn('联系客户（演示）',()=>confirm('联系客户','仅本预约详情展示完整手机号；原型不拨号。',()=>{}),{type:'secondary'}),a.status==='待确认'&&btn('确认预约',()=>go('confirm/'+a.id)),a.change&&btn('审核客户改期',()=>go('change-request/'+a.id)),a.status==='成功'&&!a.change&&btn('门诊发起改期',()=>go('reschedule/'+a.id),{type:'secondary'}),a.status==='成功'&&btn('前往扫码核销',()=>{setScanned('');setCode('');setService(false);go('scan')}),(a.status==='待确认'||a.status==='成功'&&OD.elapsed(a)<0)&&btn('无法接诊',()=>go('cancel/'+a.id),{type:'outline',status:'danger'}))));
    else if(['confirm','reschedule','change-request','cancel'].includes(page)&&a){const allowed=page==='confirm'?a.status==='待确认':page==='cancel'?['待确认','成功'].includes(a.status)&&!(a.status==='成功'&&OD.elapsed(a)>=0):a.status==='成功'&&(page!=='change-request'||!!a.change)&&(page!=='reschedule'||!a.change);body=h(React.Fragment,null,heading({confirm:'确认预约',reschedule:'门诊改期','change-request':'审核客户改期',cancel:'无法接诊'}[page],a.name),!allowed?note('该预约状态已变化，当前操作不可执行。','error'):h(AppointmentForm,{key:route,appointment:a,mode:page,onSubmit:values=>{update(d=>{const item=d.appointments.find(r=>r.id===a.id);if(page==='cancel'){if(item.status==='成功'&&OD.elapsed(item)>=0)return;item.status='取消';item.reason='门诊无法接诊：'+values.reason;item.held=0;delete item.change;}else{item.history=(item.history||[]).concat(item.date+' '+item.time+' → '+values.date+' '+values.time);item.date=values.date;item.time=values.time;item.status='成功';item.agreed=values.agreed;if(page==='change-request')delete item.change;OD.rescheduled(item);}log(d,'预约 '+item.id+' '+(page==='cancel'?'已取消，权益已释放':'时间已确认，通知客户（短信模拟）'));});go('appointment/'+a.id)}}),page==='change-request'&&a.change&&btn('拒绝改期，保留原时间',()=>confirm('拒绝改期？','原预约时间继续有效，通知客户。',()=>{update(d=>{delete d.appointments.find(r=>r.id===a.id).change;log(d,'改期未通过，原时间继续有效')});go('appointment/'+a.id)}),{type:'outline'}));}
else if(page==='scan')body=h(React.Fragment,null,heading('扫码核销','先完成约定服务，再核销权益'),h('div',{className:'scan-window'},h('div',null,h('strong',null,'扫描客户权益凭证'),h('span',{className:'muted'},'相机未接入 · 下方输入演示凭证'))),field('演示凭证',h(Input,{value:code,onChange:setCode,placeholder:'VISIT-001'})),btn('读取演示凭证',()=>{setScanned(code.trim().toUpperCase());setService(false);setError('')}),h('p',{className:'muted'},'有效：VISIT-001；到期后补核销：VISIT-ODLATE；异常：VISIT-EXPIRED / VISIT-OTHER / VISIT-FROZEN。'),field('模拟平台调价（仅评审，不是门诊业务操作）',h(Select,{value:data.currentFee||60,options:[{label:'60元 / 当前规则V1',value:60},{label:'80元 / 调价后规则V2',value:80}],onChange:value=>update(d=>{d.currentFee=value;for(const a of d.appointments)if(!a.redemptionId&&!a.used){a.fee=value;a.feeRuleVersion=value===60?'演示V1':'演示V2';}})})),scanned&&(scanError()?note(scanError(),'error'):card('核销前核对','可核销',h(React.Fragment,null,row('客户',scanAppointment.name),row('当前门诊',data.clinic),row('预约',scanAppointment.date+' '+scanAppointment.time),row('推广产品',scanAppointment.externalName||'舒适洁牙服务'),row('权益来源',scanAppointment.source),row('本次消耗',scanAppointment.quantity+'份'),row('获客费',scanAppointment.fee+'元'),h(Checkbox,{checked:service,onChange:v=>{setService(v);if(v)setError('')}},'确认客户已完成约定服务'),error&&note(error,'error')),btn('确认核销',()=>{if(!service){setError('请先确认客户已完成约定服务');return}confirm('确认本次核销？','消耗'+scanAppointment.quantity+'份权益，预约核销完成，按核销时适用规则锁定并产生'+scanAppointment.fee+'元获客服务费。',()=>{const error=scanError();if(error){setError(error);return}const rid='R-'+Date.now();update(d=>{const item=d.appointments.find(r=>r.id===scanAppointment.id);if(OD.redeemError(item))return;OD.act(item,'redeem','clinic');item.redemptionId=rid;delete item.change;d.redemptions.unshift({id:rid,appointment:item.id,externalName:item.externalName||'舒适洁牙服务',amount:item.feeSnapshot.amount,feeSnapshot:clone(item.feeSnapshot),quantity:item.quantity,settled:false,status:'已核销',time:today+' 10:30',operator:'门诊员工（演示）'});log(d,'预约 '+item.id+' 已核销，获客费已入账');});go('redemption/'+rid)})}))));
    else if(page==='redemptions')body=h(React.Fragment,null,heading('核销记录','原核销记录与撤销记录均保留'),h(StateList,{states:['已核销','已撤销'],items:data.redemptions,render:r=>h('div',{key:r.id},card(appointments.find(a=>a.id===r.appointment).name,r.status,h(React.Fragment,null,row('推广产品',r.externalName||appointments.find(a=>a.id===r.appointment).externalName||'舒适洁牙服务'),row('核销时间',r.time),row('费用',r.amount+'元'),row('原费用状态',r.settled?'已结清':'未结清')),btn('核销详情',()=>go('redemption/'+r.id),{type:'secondary'})))}));
    else if(page==='redemption'&&r){const appointment=appointments.find(a=>a.id===r.appointment),reversal=data.reversals.find(v=>v.redemption===r.id);body=h(React.Fragment,null,heading(r.status==='已撤销'?'核销已撤销':'核销成功'),card('核销明细',r.status,h(React.Fragment,null,row('编号',r.id),row('客户',appointment.name),row('推广产品',r.externalName||appointment.externalName||'舒适洁牙服务'),row('门诊',data.clinic),row('时间',r.time),row('核销数量',r.quantity+'份'),row('获客费',r.amount+'元'),row('原费用状态',r.settled?'已结清':'未结清'),row('操作人',r.operator),row('锁费时间',r.feeSnapshot?.lockedAt||'历史记录'),row('计费规则版本',r.feeSnapshot?.ruleVersion||'历史记录')),r.status==='已核销'&&!r.settled&&btn('撤销错误核销',()=>go('revoke/'+r.id),{type:'outline',status:'danger'})),reversal&&card('撤销记录','已记录',h(React.Fragment,null,row('撤销编号',reversal.id),row('原因',reversal.reason),row('费用处理',reversal.effect),note(reversal.special?'已恢复系统自动完成；权益待客户申请恢复，不生成门诊待办。':'原核销保留，预约恢复成功；权益恢复为该预约占用。如不再履约，请另行取消预约。'))),btn('返回核销记录',()=>go('redemptions'),{type:'secondary'}));}
    else if(page==='revoke'&&r)body=h(React.Fragment,null,heading('撤销错误核销'),note('此操作仅限原核销门诊员工；原记录不会删除。','warn'),row('原核销',r.id),row('费用处理',r.settled?'账单已完成结算，不能撤销':'未结清，移出有效账单并保留审计'),field('撤销原因',h(Input.TextArea,{value:reason,onChange:setReason,placeholder:'请输入错误核销的原因'})),error&&note(error,'error'),btn('提交撤销',()=>{if(r.settled){setError('账单已完成结算，不能撤销核销');return}if(r.status!=='已核销'){setError('该核销已经撤销，不能重复恢复权益');return}if(!reason.trim()){setError('请填写撤销原因');return}confirm('确认撤销核销？','未结算交易移出账单并保留审计。系统自动完成后的补核销撤销，权益转待恢复，客户申请后释放。',()=>{try{save(ClinicFinance.reverse(data,r.id,reason));go('redemption/'+r.id)}catch(e){setError(e.message)}});},{status:'danger'}));
    else if(page==='followups')body=h(React.Fragment,null,heading('过期预约待办','只在实际核销成功后计费'),note('24小时生成待办并提醒；72小时系统自动完成不核销、不释放、不计费。评审时间：2026-09-07 12:00。'),h(StateList,{states:['待处理','待补核销','异常搁置','已关闭'],items:overdueTasks,render:t=>h('div',{key:t.id},card(t.name,t.status,h(React.Fragment,null,row('任务',t.id+' · '+t.kind),row('预约',t.date+' '+t.time),t.reason&&note(t.reason)),btn('处理预约 '+t.appointment,()=>go('feedback/'+t.appointment),{type:'secondary'})))}),btn('模拟定时检查（评审）',()=>update(d=>{for(const a of d.appointments)if(a.overdueManaged)OD.check(a);log(d,'已按评审时间检查；无真实计时任务')}),{type:'outline'}));
    else if(page==='feedback'&&a)body=h(React.Fragment,null,heading('过期预约处理',a.name),h(OD.Details,{a,role:'clinic',onAction:action=>overdueAction(a.id,action),onScan:()=>{setScanned('');setCode(a.token);setService(false);go('scan')},onReschedule:()=>go('reschedule/'+a.id)}),a.status==='成功'&&btn('记录双方反馈冲突',()=>confirm('记录双方反馈冲突？','仅保留事实并停止自动处理，不裁决、不释放、不计费。',()=>update(d=>{const item=d.appointments.find(r=>r.id===a.id);item.conflict=true;item.feedback='双方反馈冲突';const t=OD.active(item);if(t)t.status='异常搁置';log(d,'双方反馈冲突，暂停自动处置')})),{type:'outline'}));
    else if(page==='bills'||page==='credit')body=h(React.Fragment,null,heading('账单与收款','按合同周结 / 月结 · 核销后计费'),riskScene==='逾期待处理'&&note('账单逾期，请尽快付款；仍可接受新预约，上下线由平台人工处理。','warn'),blocked&&note('平台已人工下线；付款不自动恢复，请联系平台核实后上线。','warn'),card('待结算费用',null,h(React.Fragment,null,row('已核销未结清',debt.toFixed(2)+'元'),note('预约不计费；核销产生获客费。渠道负责催收，不承担担保。'))),h(StateList,{states:['待付款','付款待审核','已结清','已逾期'],items:[{id:'BILL1',status:data.bill.status==='待付款'&&riskScene==='逾期待处理'?'已逾期':data.bill.status}],render:x=>card('本期周结账单',x.status,h(React.Fragment,null,row('账期','08-31 至 09-06'),row('应付',data.bill.amount.toFixed(2)+'元'),row('付款截止',data.bill.deadline)),btn('账单详情',()=>go('bill')))}),data.reversals.some(r=>r.adjustment)&&note('历史负向调整（只读旧记录，不再支持已结清撤销）：'+data.reversals.reduce((n,r)=>n+r.adjustment,0)+'元'),field('评审场景（非门诊业务操作）',h(Select,{value:riskScene,onChange:setRiskScene,options:['正常','逾期待处理','平台人工下线']})));
    else if(page==='bill')body=h(ClinicFinance.Bill,{data,save,go});
    else if(page==='messages')body=h(React.Fragment,null,heading('消息通知'),h(StateList,{states:['未读','已读'],items:data.messages,render:m=>h('div',{key:m.id},card(m.name,m.status,null,m.status==='未读'&&btn('标为已读',()=>update(d=>{d.messages.find(r=>r.id===m.id).status='已读'}),{type:'secondary'})))}));
    else if(page==='profile')body=h(React.Fragment,null,heading('门诊与员工'),card(data.clinic,'已绑定',h(React.Fragment,null,row('当前身份',data.identity),row('绑定手机号','138****0001'),row('所属渠道','启明渠道'),row('预约联系号码','138****0021'),isAdmin&&row('合同到期','2026-09-30'),note(isAdmin?'合同即将到期，请联系渠道业务员续签。账号及联系方式在Web后台维护。':'员工只处理预约及核销履约，账号由门诊后台预先开通。'))),h('div',{className:'stack'},btn('查看核销记录',()=>go('redemptions'),{type:'secondary'}),isAdmin&&btn('查看门诊合同',()=>go('contract'),{type:'secondary'}),isAdmin&&btn('账单与收款',()=>go('bills'),{type:'secondary'}),btn('消息通知',()=>go('messages'),{type:'secondary'}),btn('账号开通与绑定说明',()=>go('binding'),{type:'text'}),btn('退出登录',()=>{update(d=>{d.logged=false});setAgree(false);go('home')},{type:'outline'})));
    else body=h(React.Fragment,null,heading('未找到记录'),btn('返回工作台',()=>go('home')));
    return h(Shell,{title:'齿慧通 · 门诊端',route,go,nav,back:['appointment','confirm','reschedule','cancel','change-request'].includes(page)?'appointments':['redemption','revoke'].includes(page)?'redemptions':page==='feedback'?'followups':'home'},body);
  }
  window.MINI={role:'clinic',routes:['home','appointments','appointment/V1','confirm/V2','reschedule/V1','change-request/V3','cancel/V2','scan','redemptions','redemption/R1','revoke/R1','followups','feedback/V4','feedback/OD72','feedback/OD24','bills','bill','contract','messages','profile','binding']};
  ReactDOM.createRoot(document.getElementById('root')).render(h(arco.ConfigProvider,null,h(App)));
})();
