const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const jsQR=require('jsqr');
const root=path.resolve(__dirname,'../dist');
const id='00000000-0000-4000-8000-000000000001';
const id2='00000000-0000-4000-8000-000000000002';
const future='2030-10-01T02:00:00Z';
const appt={id,version:1,status:'success',reserved:true,clinic_name:'合成门诊',clinic_id:id2,customer_name:'合成客户',phone:'13900000000',external_name:'外部推广产品',source_name:'合成来源',benefit_id:id,scheduled_at:future,requested_at:future,expires_at:'2031-01-01T00:00:00Z',redemptions:[],reschedules:[],usage_rules:'每次一份',redemption_qr:'synthetic-credential-not-real-12345'};
const benefit={id,card_id:id,external_name:'外部推广产品',source_name:'合成来源',status:'available',available:1,pending:0,reserved:0,expires_at:appt.expires_at,usage_rules:'每次一份',can_book:true};
const bill={id,version:1,clinic_name:'合成门诊',cycle:'monthly',status:'pending_payment',total_cents:6000,received_cents:0,remaining_cents:6000,due_at:future};
const ctx=(params={})=>({params,form:{},status:'all',page:1,cache:{}});
function harness(audience='customer',role='admin'){
  const calls=[],cache={};let responder=()=>({});let responseStatus=200;let requestOverride;
  const member={id,organization_id:id2,organization_name:'合成门诊',role};
  const identity={audience,token:'synthetic-session',memberships:audience==='clinic'?[member]:undefined,profile:{number:'C0001',name:'合成客户',phone:'13900000000',gender:'unknown',age:null},has_pending_benefits:false};
  const wx={request(options){calls.push(options);if(requestOverride)return requestOverride(options);const key=options.url.split('/mini/'+audience)[1];const data=key==='/login'||key==='/me'?identity:responder(key,options);options.success({statusCode:responseStatus,data});},login(o){o.success({code:'synthetic-login-code'});},getAccountInfoSync(){return {miniProgram:{appId:'wx1111111111111111'}};},showModal(o){o.success({confirm:true});},reLaunch(o){calls.push({nav:o.url});},switchTab(o){calls.push({nav:o.url});},navigateTo(o){calls.push({nav:o.url});},navigateBack(){calls.push({nav:'back'});},setNavigationBarTitle(){},stopPullDownRefresh(){},getFileSystemManager(){return {unlink(){}};},getLocation(o){o.fail();},scanCode(o){o.success({result:appt.redemption_qr});},makePhoneCall(){},openLocation(){},requestPayment(o){calls.push({payment:true});o.success();},openPrivacyContract(o){o.success();},chooseMedia(o){o.success({tempFiles:[{tempFilePath:'/synthetic.png',size:100}]});},uploadFile(o){calls.push(o);o.success({statusCode:201,data:JSON.stringify({id})});}};
  const context=vm.createContext({wx,console,Date,Math,Map,Set,Promise,Component(){},Array,Object,Number,JSON,Error});
  function load(relative){let file=path.resolve(root,audience,relative);if(!file.endsWith('.js'))file+='.js';if(cache[file])return cache[file].exports;const module={exports:{}};cache[file]=module;const code=fs.readFileSync(file,'utf8');const fn=vm.runInContext('(function(require,module,exports){'+code+'\n})',context);fn(request=>{assert.ok(request.startsWith('.'),'no undeclared npm/native require');return load(path.relative(path.join(root,audience),path.resolve(path.dirname(file),request)));},module,module.exports);return module.exports;}
  const config=load('shared/config').config;Object.assign(config,{appid:'wx1111111111111111',apiBase:'https://synthetic.example',privacyReady:true});
  const runtime=load('shared/runtime');const screens=load('domain/screens').screens;
  return {calls,wx,identity,config,runtime,screens,load,respond(fn,status=200){responder=fn;responseStatus=status;},override(fn){requestOverride=fn;},async login(){await runtime.login('synthetic-phone-code');},page(name){const page=load('shared/controller').createPage(name,screens);page.setData=function(data){Object.assign(this.data,data);};page.onLoad({});return page;}};
}

for(const audience of ['customer','clinic'])test(audience+' independent package route and WXML contract',()=>{
  const folder=path.join(root,audience),app=JSON.parse(fs.readFileSync(path.join(folder,'app.json')));
  const h=harness(audience);
  for(const page of app.pages){for(const suffix of ['.js','.json','.wxml','.wxss'])assert.ok(fs.existsSync(path.join(folder,page+suffix)),page+suffix);
    const name=page.split('/')[1],instance=h.page(name),wxml=fs.readFileSync(path.join(folder,page+'.wxml'),'utf8');
    for(const binding of wxml.matchAll(/bind(?:tap|change|input|getphonenumber)="([a-zA-Z]+)"/g))assert.equal(typeof instance[binding[1]],'function',binding[1]);
    assert.ok(!wxml.includes('web-view'));assert.ok(wxml.includes('view.qr'));
  }
  const sources=fs.readdirSync(folder,{recursive:true}).filter(f=>f.endsWith('.js')).map(f=>fs.readFileSync(path.join(folder,f),'utf8')).join('\n');
  assert.ok(!sources.includes('synthetic-session'));assert.ok(!sources.includes('setStorageSync'));assert.ok(!sources.includes('Basic '));assert.ok(!sources.includes('appSecret'));assert.ok(!sources.includes('localhost'));
  assert.equal(h.load('shared/config').config.audience,audience);
  if(audience==='customer')assert.ok(!sources.includes("/bills/"));
  const realConfig=JSON.parse(fs.readFileSync(path.join(folder,'project.config.json')));assert.equal(realConfig.appid,'touristappid');assert.equal(realConfig.setting.urlCheck,true);
});
test('unconfigured app cannot attempt network authorization',async()=>{const h=harness();h.config.appid='touristappid';await assert.rejects(h.login(),/账号尚未配置/);assert.equal(h.calls.length,0);});
test('phone authorization does not accept a self-reported phone or openid',async()=>{const h=harness();await h.login();const call=h.calls[0];assert.deepEqual(Object.keys(call.data).sort(),['login_code','phone_code']);assert.equal(h.runtime.current().audience,'customer');});
test('network-uncertain writes preserve the same idempotency key',async()=>{const h=harness();await h.login();h.override(o=>o.fail());await assert.rejects(h.runtime.request('/cards/'+id+'/claim','POST',{confirmed:true},true),/网络/);const key=h.calls.at(-1).header['Idempotency-Key'];h.override(o=>o.success({statusCode:200,data:{}}));await h.runtime.request('/cards/'+id+'/claim','POST',{confirmed:true},true);assert.equal(h.calls.at(-1).header['Idempotency-Key'],key);});
test('session change discards an in-flight response',async()=>{const h=harness();await h.login();let pending;h.override(o=>{pending=o;});const result=h.runtime.request('/benefits');h.runtime.clearSession();pending.success({statusCode:200,data:{secret:'old'}});await assert.rejects(result,/身份已切换/);});
test('unauthorized response clears session',async()=>{const h=harness();await h.login();h.respond(()=>({message:'登录失效'}),401);await assert.rejects(h.runtime.request('/benefits'),/登录失效/);assert.equal(h.runtime.current(),null);});
test('membership header and protected page guard separate employees',async()=>{const h=harness('clinic','staff');await h.login();assert.equal(h.runtime.headers()['X-Membership-ID'],id);const page=h.page('bills');await page.onShow();assert.match(page.data.error,/仅门诊管理员/);assert.equal(h.calls.some(c=>c.url?.endsWith('/bills')),false);});
test('date conversion uses China timezone and enforces expiry date',()=>{const h=harness();assert.equal(h.load('shared/model').dateText('2026-09-13T18:30:00Z'),'2026-09-14 02:30');assert.throws(()=>h.load('shared/screens').checkTime({date:'2031-01-02',time:'10:00'},'2031-01-01T23:00:00+08:00'),/有效期/);});
test('benefit card renders rules and direct appointment action',async()=>{const h=harness();h.respond(()=>({results:[benefit],total:1,counts:{all:1,available:1}}));const view=await h.screens.benefits.load(ctx());assert.ok(view.rows[0].lines.some(v=>v.includes('每次一份')));assert.equal(view.rows[0].actions[0].label,'预约门诊');});
test('location refusal leaves manual search available',async()=>{const h=harness();h.respond(p=>p.startsWith('/benefits')?{results:[benefit],total:1}:{results:[],total:0});const c=ctx({benefit_id:id});await h.screens.clinics.action(c,'locate');const v=await h.screens.clinics.load(c);assert.match(v.notice,/输入城市/);assert.ok(v.fields.some(f=>f.key==='query'));});
test('customer QR displayed directly, but blocked for pending reschedule',async()=>{const h=harness();h.respond(()=>({...appt}));let v=await h.screens.appointment.load(ctx({id}));assert.equal(v.qr,appt.redemption_qr);h.respond(()=>({...appt,pending_reschedule:{id}}));v=await h.screens.appointment.load(ctx({id}));assert.equal(v.qr,'');});
test('system-completed/clinic-absent/restoring show distinct customer actions',async()=>{const h=harness();for(const [extra,key] of [[{status:'completed',completion_source:'system'},'feedback-no'],[{status:'cancelled',clinic_absent_at:future},'feedback-no'],[{status:'completed',completion_source:'system',restoration_pending:true},'restore']]){h.respond(()=>({...appt,...extra}));const v=await h.screens.appointment.load(ctx({id}));assert.ok(v.actions.some(a=>a.key===key));}});
test('read message is not the restoration operation',async()=>{const h=harness();h.respond(()=>({}));const c=ctx();c.cache.rows=[{id,appointment_id:id2}];await h.screens.messages.action(c,'message',id);assert.ok(h.calls.some(c=>c.url?.endsWith('/messages/'+id+'/read')));assert.ok(!h.calls.some(c=>c.url?.endsWith('/restore')));});
test('clinic reschedule requires explicit agreement',async()=>{const h=harness('clinic');const c=ctx({action:'reschedule'});c.cache.object=appt;c.form={date:'2030-10-02',time:'10:00'};await assert.rejects(h.screens['appointment-action'].submit(c),/协商一致/);assert.equal(h.calls.length,0);});
test('cancelled confirmation leaves business state unchanged',async()=>{const h=harness();h.wx.showModal=o=>o.success({confirm:false});const ok=await h.load('shared/screens').command('/a',{confirmed:true},'confirm');assert.equal(ok,false);assert.equal(h.calls.length,0);});
test('scan quote requires treatment acknowledgement and scoped appointment',async()=>{const h=harness('clinic');await h.login();h.respond(p=>p==='/redemptions/scan'?{results:[appt]}:p==='/redemptions/quote'?{quote:'signed-synthetic',version:1,units:1,fee_cents:6000}:{});const c=ctx({appointment_id:id});await h.screens.scan.action(c,'scan-code');await h.screens.scan.action(c,'quote',id);await assert.rejects(h.screens.scan.submit(c),/完成治疗/);c.form.treated=true;await h.screens.scan.submit(c);const call=h.calls.find(c=>c.url?.endsWith('/redemptions'));assert.equal(call.data.quote,'signed-synthetic');assert.equal(call.data.appointment_id,id);assert.ok(call.header['Idempotency-Key']);assert.equal(c.cache.credential,undefined);});
test('settled redemption cannot be reversed by UI or direct submit',async()=>{const h=harness('clinic');h.respond(()=>({...appt,status:'completed',redemptions:[{id,status:'active',clinic_settled:true}]}));const c=ctx({id,action:'reverse'});const v=await h.screens.appointment.load(c);assert.ok(!v.actions.some(a=>a.key==='reverse'));await assert.rejects(h.screens['appointment-action'].submit(c),/已结清/);});
test('payment simulated success never calls wx.requestPayment',async()=>{const h=harness('clinic');await h.login();h.respond(p=>p.includes('/payments?')?{results:[]}:p.endsWith('/query')?{id,status:'success',simulated:true}:p.endsWith('/payment')?{id,status:'pending',simulated:true}:bill);const c=ctx({id});await h.screens.payment.load(c);await h.screens.payment.action(c,'pay');assert.ok(!h.calls.some(c=>c.payment));assert.equal(c.cache.payment.status,'success');assert.match((await h.screens.payment.load(c)).notice,/未产生真实资金/);});
test('real wx payment callback is followed by server query',async()=>{const h=harness('clinic');await h.login();h.respond(p=>p.includes('/payments?')?{results:[]}:p.endsWith('/query')?{id,status:'unknown'}:p.endsWith('/payment')?{id,status:'pending',payment_parameters:{timeStamp:'1',nonceStr:'n',package:'p',signType:'RSA',paySign:'synthetic'}}:bill);const c=ctx({id});await h.screens.payment.load(c);await h.screens.payment.action(c,'pay');assert.ok(h.calls.some(c=>c.payment));assert.equal(c.cache.payment.status,'unknown');assert.ok(!(await h.screens.payment.load(c)).actions.some(a=>a.key==='pay'));});
test('receipt upload uses payment purpose and does not force multipart boundary',async()=>{const h=harness('clinic');await h.login();await h.load('domain/attachments').uploadReceipt();const call=h.calls.find(c=>c.filePath);assert.equal(call.formData.purpose,'payment');assert.equal(call.header['Content-Type'],undefined);});
test('native tab navigation carries scan context in memory not credential URL',()=>{const h=harness('clinic');h.runtime.go('scan',{appointment_id:id});assert.equal(h.calls[0].nav,'/pages/scan/index');assert.equal(h.runtime.consumeNavigation().appointment_id,id);assert.equal(Object.keys(h.runtime.consumeNavigation()).length,0);});
test('page hide clears sensitive display and prevents stale async render',async()=>{const h=harness();await h.login();const page=h.page('benefits');h.respond(()=>({results:[benefit],total:1}));await page.onShow();assert.equal(page.data.view.rows.length,1);page.onHide();assert.equal(page.data.view.rows,undefined);assert.equal(page.data.view.qr,undefined);});
test('QR matrix is deterministic with standard finder patterns',()=>{const h=harness();const {matrix}=h.load('shared/qr');const a=matrix(appt.redemption_qr),b=matrix(appt.redemption_qr);assert.equal(a.length,b.length);assert.equal(JSON.stringify(a),JSON.stringify(b));assert.equal((a.length-17)%4,0);for(let x=0;x<7;x++)assert.equal(a[0][x],true);assert.equal(a[1][1],false);assert.equal(a[3][3],true);assert.throws(()=>matrix(''),/凭证无效/);});
test('payment re-entry recovers existing pending order and prevents new payment',async()=>{const h=harness('clinic');await h.login();h.respond(p=>p.includes('/payments?')?{results:[{id,status:'pending',method:'jsapi',payment_parameters:{}}]}:bill);const c=ctx({id});const view=await h.screens.payment.load(c);assert.equal(c.cache.payment.id,id);assert.ok(!view.actions.some(a=>a.key==='pay'));await assert.rejects(h.screens.payment.action(c,'pay'),/已有支付单/);});
test('all customer page loaders produce explicit business views',async()=>{const h=harness();await h.login();h.respond(p=>p.startsWith('/benefits')?{results:[benefit],total:1}:p.startsWith('/appointments/')?appt:p.startsWith('/clinics/')?{id:id2,name:'合成门诊',address:'合成地址',province:'北京',city:'北京',district:'海淀',latitude:39.9,longitude:116.3}:p.startsWith('/clinics?')?{results:[],total:0}:p.startsWith('/messages')?{results:[],total:0}:p.startsWith('/appointments')?{results:[appt],total:1}:{});for(const name of Object.keys(h.screens)){const c=ctx({id,benefit_id:id,clinic_id:id2,action:'reschedule'});const view=await h.screens[name].load(c);assert.equal(typeof view.title,'string',name);assert.ok(view.title.length,name);}});
test('clinic cooperation follows server clinic ID, not organization ID',async()=>{const h=harness('clinic');await h.login();h.respond(p=>p.includes('/cooperation')?{products_endpoint:'/api/v1/mini/clinic/clinics/'+id+'/products'}:{results:[],total:0});await h.screens.products.load(ctx());assert.ok(h.calls.some(c=>c.url?.includes('/clinics/'+id+'/products')));assert.ok(!h.calls.some(c=>c.url?.includes('/clinics/'+id2+'/products')));});
test('role downgrade erases previously displayed administrator data',async()=>{const h=harness('clinic');await h.login();h.respond(()=>({results:[bill],total:1}));const p=h.page('bills');await p.onShow();assert.equal(p.data.view.rows.length,1);p.onHide();h.identity.memberships[0].role='staff';await p.onShow();assert.match(p.data.error,/仅门诊管理员/);assert.equal(p.data.view.rows,undefined);});
test('actual rendered QR pixels round trip through independent decoder',()=>{const h=harness();const matrix=h.load('shared/qr').matrix;for(const value of [appt.redemption_qr,'A'.repeat(100),'X_0123456789-'.repeat(15)]){const cells=matrix(value),scale=8,padding=4,size=(cells.length+padding*2)*scale,pixels=new Uint8ClampedArray(size*size*4);pixels.fill(255);cells.forEach((row,y)=>row.forEach((dark,x)=>{if(dark)for(let yy=0;yy<scale;yy++)for(let xx=0;xx<scale;xx++){const pos=(((y+padding)*scale+yy)*size+(x+padding)*scale+xx)*4;pixels[pos]=pixels[pos+1]=pixels[pos+2]=29;}}));assert.equal(jsQR(pixels,size,size)?.data,value);}});
test('all clinic loaders map server projections without raw object dumps',async()=>{const h=harness('clinic');await h.login();const change={id,version:1,status:'pending',appointment_id:id,proposed_at:future};h.respond(p=>p.startsWith('/workbench/tasks/')?{record:appt}:p.startsWith('/workbench/tasks?')?{results:[],total:0}:p==='/workbench'?{tasks:{categories:{appointment_confirmation:{pending:2}}}}:p.startsWith('/appointments/')?{...appt,reschedules:[change]}:p.startsWith('/organizations/')&&p.includes('/cooperation')?{current_contract:{id,number:'HT001',revision:1,status:'approved'},products_endpoint:'/api/v1/mini/clinic/clinics/'+id+'/products'}:p.startsWith('/contracts/')?{id,number:'HT001',products:[],attachment_ids:[],revision:1}:p.includes('/payments?')?{results:[]}:p.match(/\/bills\/[a-f0-9-]+$/)?bill:{results:[],total:0});for(const name of Object.keys(h.screens)){const c=ctx({id,action:'confirm',type:'appointment'});const view=await h.screens[name].load(c);assert.equal(typeof view.title,'string',name);assert.ok(!JSON.stringify(view).includes('[object Object]'),name);}});
