# Generated by Django 5.2.17 on 2026-09-11 17:57

import chihuitong.crypto
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('phone', chihuitong.crypto.EncryptedTextField()),
                ('phone_index', models.CharField(max_length=64, unique=True)),
                ('name', chihuitong.crypto.EncryptedTextField()),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessCalendar',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('working', models.BooleanField()),
                ('note', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LoginChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('phone_index', models.CharField(max_length=64, unique=True)),
                ('code_digest', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('consumed', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RateBucket',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('window', models.DateTimeField()),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('actor_id', models.UUIDField()),
                ('operation', models.CharField(max_length=80)),
                ('key', models.CharField(max_length=128)),
                ('request_digest', models.CharField(max_length=64)),
                ('result', chihuitong.crypto.EncryptedJSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('actor_id', 'operation', 'key'), name='operation_retry')],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('platform', '平台'), ('insurance', '保险公司'), ('bank', '银行'), ('broker', '经纪代理公司'), ('channel', '门诊渠道公司'), ('clinic', '口腔门诊')], max_length=16)),
                ('status', models.CharField(default='active', max_length=16)),
                ('details', chihuitong.crypto.EncryptedJSONField(default=dict)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('kind', 'platform')), fields=('kind',), name='one_platform'), models.CheckConstraint(condition=models.Q(('status__in', ['active', 'disabled'])), name='organization_state')],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('role', models.CharField(choices=[('admin', '管理员'), ('staff', '业务员/员工')], max_length=16)),
                ('active', models.BooleanField(default=True)),
                ('platform_created', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='chihuitong.account')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chihuitong.organization')),
            ],
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('object_type', models.CharField(max_length=80)),
                ('object_id', models.UUIDField()),
                ('action', models.CharField(max_length=80)),
                ('reason', chihuitong.crypto.EncryptedTextField(default='')),
                ('metadata', models.JSONField(default=dict)),
                ('request_id', models.UUIDField(null=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='chihuitong.account')),
                ('membership', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='chihuitong.membership')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='chihuitong.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Outbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('kind', models.CharField(max_length=40)),
                ('dedup_key', models.CharField(max_length=200, unique=True)),
                ('payload', chihuitong.crypto.EncryptedJSONField(default=dict)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('available_at', models.DateTimeField()),
                ('locked_until', models.DateTimeField(null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'available_at'], name='chihuitong__status_23f2e4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('token_digest', models.CharField(max_length=64, unique=True)),
                ('audience', models.CharField(default='web', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chihuitong.account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('account', 'organization'), name='one_membership'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['admin', 'staff'])), name='member_role'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.CheckConstraint(condition=models.Q(('platform_created', False), ('role', 'admin'), _connector='OR'), name='initial_admin_role'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['object_type', 'object_id', 'id'], name='chihuitong__object__692083_idx'),
        ),
    ]
