# Generated by Django 5.2.17 on 2026-09-11 18:12

import chihuitong.crypto
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chihuitong', '0002_audit_append_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('mode', models.CharField(default='percent', max_length=16)),
                ('value', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('status', models.CharField(default='active', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('profile', chihuitong.crypto.EncryptedJSONField(default=dict)),
                ('profile_version', models.PositiveIntegerField(default=0)),
                ('review_status', models.CharField(default='draft', max_length=16)),
                ('service_status', models.CharField(default='offline', max_length=16)),
                ('confirmation_hours', models.PositiveIntegerField(default=24)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_clinics', to='chihuitong.organization')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='clinic', to='chihuitong.organization')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_clinics', to='chihuitong.membership')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicProfileChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('base_version', models.PositiveIntegerField()),
                ('before', chihuitong.crypto.EncryptedJSONField(default=dict)),
                ('after', chihuitong.crypto.EncryptedJSONField(default=dict)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('reason', chihuitong.crypto.EncryptedTextField(default='')),
                ('due_at', models.DateTimeField()),
                ('reviewed_at', models.DateTimeField(null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profile_changes', to='chihuitong.clinic')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profile_reviews', to='chihuitong.membership')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chihuitong.membership')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('kind', models.CharField(choices=[('resource', '平台—资源方'), ('channel', '平台—渠道'), ('clinic', '平台—渠道—门诊')], max_length=16)),
                ('number', models.CharField(max_length=80, unique=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contract', to='chihuitong.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContractProductRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('revision', models.PositiveIntegerField()),
                ('snapshot', models.JSONField()),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chihuitong.contractproduct')),
            ],
        ),
        migrations.CreateModel(
            name='ContractVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('revision', models.PositiveIntegerField()),
                ('status', models.CharField(default='draft', max_length=16)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('settlement_cycle', models.CharField(default='monthly', max_length=16)),
                ('contact', chihuitong.crypto.EncryptedJSONField(default=dict)),
                ('attachment_ids', models.JSONField(default=list)),
                ('submitted_at', models.DateTimeField(null=True)),
                ('due_at', models.DateTimeField(null=True)),
                ('reviewed_at', models.DateTimeField(null=True)),
                ('reason', chihuitong.crypto.EncryptedTextField(default='')),
                ('channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tripartite_versions', to='chihuitong.organization')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='chihuitong.contract')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_reviews', to='chihuitong.membership')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chihuitong.membership')),
            ],
        ),
        migrations.AddField(
            model_name='contractproduct',
            name='contract_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='chihuitong.contractversion'),
        ),
        migrations.CreateModel(
            name='FileAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('original_name', chihuitong.crypto.EncryptedTextField()),
                ('storage_key', models.CharField(max_length=100, unique=True)),
                ('content_type', models.CharField(max_length=100)),
                ('size', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('purpose', models.CharField(max_length=30)),
                ('status', models.CharField(default='ready', max_length=16)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chihuitong.organization')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chihuitong.account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AttachmentLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('object_type', models.CharField(max_length=40)),
                ('object_id', models.UUIDField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='links', to='chihuitong.fileasset')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('internal_name', models.CharField(max_length=160, unique=True)),
                ('external_name', models.CharField(max_length=160)),
                ('status', models.CharField(default='active', max_length=16)),
                ('product_type', models.CharField(default='service', max_length=20)),
                ('usage_rules', models.TextField()),
                ('redemption_units', models.PositiveIntegerField(default=1)),
                ('fee_cents', models.PositiveBigIntegerField()),
                ('validity_days', models.PositiveIntegerField(default=180)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('redemption_units__gt', 0)), name='positive_redemption_units'), models.CheckConstraint(condition=models.Q(('validity_days__gt', 0)), name='positive_validity_days'), models.CheckConstraint(condition=models.Q(('status__in', ['active', 'disabled'])), name='product_state')],
            },
        ),
        migrations.AddField(
            model_name='contractproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chihuitong.product'),
        ),
        migrations.CreateModel(
            name='ClinicProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(default='offline', max_length=16)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='chihuitong.clinic')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chihuitong.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('revision', models.PositiveIntegerField()),
                ('snapshot', models.JSONField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='chihuitong.product')),
            ],
        ),
        migrations.CreateModel(
            name='SourceBrand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=160)),
                ('status', models.CharField(default='active', max_length=16)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chihuitong.organization')),
            ],
        ),
        migrations.AddConstraint(
            model_name='clinic',
            constraint=models.CheckConstraint(condition=models.Q(('confirmation_hours__gt', 0)), name='positive_confirm_hours'),
        ),
        migrations.AddConstraint(
            model_name='clinic',
            constraint=models.CheckConstraint(condition=models.Q(('service_status__in', ['online', 'offline', 'paused', 'exited'])), name='clinic_service_state'),
        ),
        migrations.AddConstraint(
            model_name='clinicprofilechange',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('clinic',), name='one_pending_profile'),
        ),
        migrations.AddConstraint(
            model_name='contractproductrevision',
            constraint=models.UniqueConstraint(fields=('term', 'revision'), name='term_revision'),
        ),
        migrations.AddConstraint(
            model_name='contractversion',
            constraint=models.UniqueConstraint(fields=('contract', 'revision'), name='contract_revision'),
        ),
        migrations.AddConstraint(
            model_name='contractversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('contract',), name='one_pending_contract'),
        ),
        migrations.AddConstraint(
            model_name='contractversion',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='contract_dates'),
        ),
        migrations.AddConstraint(
            model_name='contractversion',
            constraint=models.CheckConstraint(condition=models.Q(('settlement_cycle__in', ['weekly', 'monthly'])), name='contract_cycle'),
        ),
        migrations.AddConstraint(
            model_name='attachmentlink',
            constraint=models.UniqueConstraint(fields=('asset', 'object_type', 'object_id'), name='unique_attachment_link'),
        ),
        migrations.AddConstraint(
            model_name='contractproduct',
            constraint=models.UniqueConstraint(fields=('contract_version', 'product'), name='one_product_per_version'),
        ),
        migrations.AddConstraint(
            model_name='contractproduct',
            constraint=models.CheckConstraint(condition=models.Q(('value__gte', 0)), name='nonnegative_split'),
        ),
        migrations.AddConstraint(
            model_name='contractproduct',
            constraint=models.CheckConstraint(condition=models.Q(('mode__in', ['percent', 'amount'])), name='split_mode'),
        ),
        migrations.AddConstraint(
            model_name='contractproduct',
            constraint=models.CheckConstraint(condition=models.Q(('mode', 'amount'), ('value__lte', 100), _connector='OR'), name='split_percent_limit'),
        ),
        migrations.AddConstraint(
            model_name='clinicproduct',
            constraint=models.UniqueConstraint(fields=('clinic', 'product'), name='one_clinic_product'),
        ),
        migrations.AddConstraint(
            model_name='productrevision',
            constraint=models.UniqueConstraint(fields=('product', 'revision'), name='product_revision'),
        ),
        migrations.AddConstraint(
            model_name='sourcebrand',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='brand_per_resource'),
        ),
    ]
