# Generated by Django 5.2.17 on 2026-09-11 18:30

import chihuitong.crypto
import chihuitong.models.sales
import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chihuitong', '0003_contractproduct_clinic_clinicprofilechange_contract_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardSequence',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('next_number', models.PositiveBigIntegerField(default=100000000000)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('number', models.CharField(default=chihuitong.models.sales.customer_number, editable=False, max_length=40, unique=True)),
                ('phone', chihuitong.crypto.EncryptedTextField()),
                ('phone_index', models.CharField(max_length=64, unique=True)),
                ('name', chihuitong.crypto.EncryptedTextField()),
                ('profile', chihuitong.crypto.EncryptedJSONField(default=dict)),
                ('registered_at', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('serial', models.PositiveBigIntegerField(unique=True)),
                ('credential', chihuitong.crypto.EncryptedTextField()),
                ('credential_digest', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(default='unclaimed', max_length=16)),
                ('frozen', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(null=True)),
                ('voided_at', models.DateTimeField(null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='chihuitong.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sources', to='chihuitong.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chihuitong.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('total', models.PositiveIntegerField()),
                ('pending', models.PositiveIntegerField(default=0)),
                ('available', models.PositiveIntegerField(default=0)),
                ('reserved', models.PositiveIntegerField(default=0)),
                ('used', models.PositiveIntegerField(default=0)),
                ('restoring', models.PositiveIntegerField(default=0)),
                ('voided', models.PositiveIntegerField(default=0)),
                ('activated_at', models.DateTimeField(null=True)),
                ('expires_at', models.DateTimeField(null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chihuitong.product')),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='benefit', to='chihuitong.card')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='benefits', to='chihuitong.customer')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chihuitong.customersource')),
            ],
        ),
        migrations.CreateModel(
            name='DomainEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(max_length=40)),
                ('object_id', models.UUIDField()),
                ('payload', models.JSONField(default=dict)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chihuitong.card')),
            ],
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(default='uploaded', max_length=20)),
                ('configuration', models.JSONField(default=dict)),
                ('sheets', models.JSONField(default=list)),
                ('preview', chihuitong.crypto.EncryptedJSONField(default=dict)),
                ('mapping_digest', models.CharField(blank=True, max_length=64)),
                ('confirmed_at', models.DateTimeField(null=True)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('processed_rows', models.PositiveIntegerField(default=0)),
                ('error_rows', models.PositiveIntegerField(default=0)),
                ('total_cards', models.PositiveIntegerField(default=0)),
                ('failure_code', models.CharField(blank=True, max_length=80)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chihuitong.fileasset')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chihuitong.membership')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chihuitong.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImportFormat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=100)),
                ('structure', models.JSONField(default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chihuitong.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('row_number', models.PositiveIntegerField()),
                ('raw', chihuitong.crypto.EncryptedJSONField(default=dict)),
                ('normalized', chihuitong.crypto.EncryptedJSONField(default=dict)),
                ('errors', models.JSONField(default=list)),
                ('status', models.CharField(default='valid', max_length=16)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rows', to='chihuitong.importbatch')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('mode', models.CharField(max_length=16)),
                ('entry', models.CharField(max_length=16)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price_cents', models.PositiveBigIntegerField(default=0)),
                ('total_cents', models.PositiveBigIntegerField()),
                ('received_cents', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(default='draft', max_length=24)),
                ('previous_status', models.CharField(blank=True, max_length=24)),
                ('validity_days', models.PositiveIntegerField(default=180)),
                ('units_per_card', models.PositiveIntegerField(default=1)),
                ('product_snapshot', models.JSONField(default=dict)),
                ('source_name', models.CharField(max_length=160)),
                ('submitted_at', models.DateTimeField(null=True)),
                ('approved_at', models.DateTimeField(null=True)),
                ('reason', chihuitong.crypto.EncryptedTextField(default='')),
                ('shipment', chihuitong.crypto.EncryptedJSONField(default=dict)),
                ('refund', chihuitong.crypto.EncryptedJSONField(default=dict)),
                ('import_batch', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='chihuitong.importbatch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chihuitong.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chihuitong.product')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chihuitong.membership')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_reviews', to='chihuitong.membership')),
                ('source_brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chihuitong.sourcebrand')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('amount_cents', models.PositiveBigIntegerField()),
                ('paid_at', models.DateTimeField()),
                ('payer', chihuitong.crypto.EncryptedTextField()),
                ('reference', chihuitong.crypto.EncryptedTextField()),
                ('reference_index', models.CharField(max_length=64)),
                ('attachment_ids', models.JSONField(default=list)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('reviewed_at', models.DateTimeField(null=True)),
                ('reason', chihuitong.crypto.EncryptedTextField(default='')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_reviews', to='chihuitong.membership')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chihuitong.membership')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='chihuitong.salesorder')),
            ],
        ),
        migrations.CreateModel(
            name='CardRange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('first_number', models.PositiveBigIntegerField(unique=True)),
                ('last_number', models.PositiveBigIntegerField(unique=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='number_range', to='chihuitong.salesorder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='card',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='chihuitong.salesorder'),
        ),
        migrations.CreateModel(
            name='SalesRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('row_number', models.PositiveIntegerField()),
                ('raw', chihuitong.crypto.EncryptedJSONField(default=dict)),
                ('normalized', chihuitong.crypto.EncryptedJSONField(default=dict)),
                ('quantity', models.PositiveIntegerField()),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='chihuitong.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rows', to='chihuitong.salesorder')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='row',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='chihuitong.salesrow'),
        ),
        migrations.AddConstraint(
            model_name='customersource',
            constraint=models.UniqueConstraint(fields=('customer', 'organization'), name='customer_source_relation'),
        ),
        migrations.AddConstraint(
            model_name='benefit',
            constraint=models.CheckConstraint(condition=models.Q(('total', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('pending'), '+', models.F('available')), '+', models.F('reserved')), '+', models.F('used')), '+', models.F('restoring')), '+', models.F('voided')))), name='benefit_quantity_conservation'),
        ),
        migrations.AddIndex(
            model_name='domainevent',
            index=models.Index(fields=['card', 'occurred_at', 'id'], name='chihuitong__card_id_4ede78_idx'),
        ),
        migrations.AddConstraint(
            model_name='importrow',
            constraint=models.UniqueConstraint(fields=('batch', 'row_number'), name='import_original_row'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='sales_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.CheckConstraint(condition=models.Q(('units_per_card__gt', 0)), name='card_units_positive'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.CheckConstraint(condition=models.Q(('total_cents', django.db.models.expressions.CombinedExpression(models.F('quantity'), '*', models.F('unit_price_cents')))), name='sales_total_consistent'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.CheckConstraint(condition=models.Q(('mode__in', ['named', 'physical'])), name='sales_mode'),
        ),
        migrations.AddConstraint(
            model_name='purchasereceipt',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('order',), name='one_pending_purchase_receipt'),
        ),
        migrations.AddConstraint(
            model_name='purchasereceipt',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'approved')), fields=('reference_index',), name='purchase_receipt_reference'),
        ),
        migrations.AddConstraint(
            model_name='salesrow',
            constraint=models.UniqueConstraint(fields=('order', 'row_number'), name='sales_original_row'),
        ),
    ]
