# Generated by Django 5.2.17 on 2026-09-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chihuitong', '0005_appointment_clinicbill_billrevision_clinicreceipt_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='financefeedback',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('clinic_bill__isnull', False), ('partner_bill__isnull', True)), models.Q(('clinic_bill__isnull', True), ('partner_bill__isnull', False)), _connector='OR'), name='feedback_exactly_one_bill'),
        ),
    ]
