# Generated by Django 5.2.17 on 2026-09-11 19:12

import chihuitong.crypto
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chihuitong', '0006_financefeedback_feedback_exactly_one_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('notification_id', models.CharField(max_length=100, unique=True)),
                ('payload', chihuitong.crypto.EncryptedJSONField()),
                ('body_digest', models.CharField(max_length=64)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('processed_at', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='appid',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='expires_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='mchid',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='request_key',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('request_key', ''), _negated=True), fields=('created_by', 'request_key'), name='payment_request_once'),
        ),
        migrations.AddField(
            model_name='paymentnotification',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chihuitong.paymentattempt'),
        ),
    ]
