# Generated by Django 5.2.17 on 2026-09-11 19:22

import chihuitong.crypto
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chihuitong', '0007_paymentnotification_paymentattempt_appid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
                ('parameter_names', models.JSONField(default=list)),
                ('provider_template_id', models.CharField(blank=True, max_length=100)),
                ('sign_name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(default='disabled', max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SmsDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('dedup_key', models.CharField(max_length=200, unique=True)),
                ('template_version', models.PositiveIntegerField()),
                ('phone', chihuitong.crypto.EncryptedTextField()),
                ('parameters', chihuitong.crypto.EncryptedJSONField(default=dict)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('provider_reference', chihuitong.crypto.EncryptedTextField(default='')),
                ('last_error_code', models.CharField(blank=True, max_length=80)),
                ('accepted_at', models.DateTimeField(null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chihuitong.smstemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('dedup_key', models.CharField(max_length=200)),
                ('kind', models.CharField(max_length=80)),
                ('object_type', models.CharField(max_length=80)),
                ('object_id', models.UUIDField()),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(default='unread', max_length=16)),
                ('read_at', models.DateTimeField(null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chihuitong.membership')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('recipient', 'dedup_key'), name='notification_recipient_once')],
            },
        ),
    ]
