# Generated by Django 5.2.17 on 2026-09-11 19:32

import chihuitong.crypto
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chihuitong', '0008_smstemplate_smsdelivery_notification'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='organization',
            name='organization_state',
        ),
        migrations.AddField(
            model_name='auditevent',
            name='actor_name',
            field=chihuitong.crypto.EncryptedTextField(default=''),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='actor_role',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='organization_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['active', 'disabled', 'pending', 'rejected'])), name='organization_state'),
        ),
    ]
