# Generated by Django 5.2.17 on 2026-09-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chihuitong', '0010_domain_events_append_only'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='domainevent',
            index=models.Index(fields=['object_id', 'kind', 'occurred_at'], name='chihuitong__object__360ddc_idx'),
        ),
    ]
