# Generated by Django 5.2.17 on 2026-09-11 19:59

import chihuitong.crypto
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chihuitong', '0011_domainevent_chihuitong__object__360ddc_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('number', models.PositiveIntegerField()),
                ('template_version', models.PositiveIntegerField()),
                ('template_snapshot', models.JSONField(default=dict)),
                ('status', models.CharField(default='sending', max_length=16)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('provider_reference', chihuitong.crypto.EncryptedTextField(default='')),
                ('finished_at', models.DateTimeField(null=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='chihuitong.smsdelivery')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('delivery', 'number'), name='sms_attempt_number')],
            },
        ),
    ]
