# Generated by Django 5.2.17 on 2026-09-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chihuitong', '0012_smsattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='outbox',
            name='claim_token',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='issue_failure_code',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
