# Generated by Django 5.2.17 on 2026-09-11 20:19

import chihuitong.crypto
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chihuitong', '0013_outbox_claim_token_salesorder_issue_failure_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniCodeUse',
            fields=[
                ('digest', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MiniIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('audience', models.CharField(max_length=16)),
                ('appid', models.CharField(max_length=40)),
                ('openid_index', models.CharField(max_length=64)),
                ('openid', chihuitong.crypto.EncryptedTextField()),
                ('phone_index', models.CharField(max_length=64)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='chihuitong.account')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='chihuitong.customer')),
            ],
        ),
        migrations.CreateModel(
            name='MiniSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('token_digest', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(null=True)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chihuitong.miniidentity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='miniidentity',
            constraint=models.UniqueConstraint(fields=('appid', 'openid_index'), name='mini_application_identity'),
        ),
        migrations.AddConstraint(
            model_name='miniidentity',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('account__isnull', True), ('audience', 'customer'), ('customer__isnull', False)), models.Q(('account__isnull', False), ('audience', 'clinic'), ('customer__isnull', True)), _connector='OR'), name='mini_identity_audience_owner'),
        ),
    ]
