# Generated by Django 5.2.17 on 2026-09-11 20:32

import chihuitong.crypto
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chihuitong', '0014_minicodeuse_miniidentity_minisession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='payer_openid',
            field=chihuitong.crypto.EncryptedTextField(default=''),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='preparation_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='preparation_started_at',
            field=models.DateTimeField(null=True),
        ),
    ]
