# Generated by Django 5.2.17 on 2026-09-16 04:13

import chihuitong.crypto
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chihuitong', '0016_publish_approved_clinic_coordinates'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstantRedemptionOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('amount_cents', models.PositiveBigIntegerField()),
                ('snapshot', models.JSONField()),
                ('appointment_version', models.PositiveIntegerField()),
                ('paid_at', models.DateTimeField(null=True)),
                ('error_code', models.CharField(blank=True, max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name='redemption',
            name='payment_mode',
            field=models.CharField(default='postpaid', max_length=16),
        ),
        migrations.AlterField(
            model_name='clinicbill',
            name='clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='chihuitong.clinic'),
        ),
        migrations.AlterField(
            model_name='paymentattempt',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_attempts', to='chihuitong.clinicbill'),
        ),
        migrations.CreateModel(
            name='ClinicAgreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('number', models.CharField(max_length=80)),
                ('revision', models.PositiveIntegerField()),
                ('status', models.CharField(default='draft', max_length=16)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('payment_mode', models.CharField(max_length=16)),
                ('settlement_cycle', models.CharField(default='', max_length=16)),
                ('contact', chihuitong.crypto.EncryptedJSONField(default=dict)),
                ('product_ids', models.JSONField(default=list)),
                ('attachment_ids', models.JSONField(default=list)),
                ('signed_attachment_ids', models.JSONField(default=list)),
                ('paper', chihuitong.crypto.EncryptedJSONField(default=dict)),
                ('content_status', models.CharField(default='pending', max_length=16)),
                ('submitted_at', models.DateTimeField(null=True)),
                ('due_at', models.DateTimeField(null=True)),
                ('reviewed_at', models.DateTimeField(null=True)),
                ('reason', chihuitong.crypto.EncryptedTextField(default='')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agreement_reviews', to='chihuitong.membership')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chihuitong.membership')),
            ],
        ),
        migrations.CreateModel(
            name='AgreementClinic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreement_coverage', to='chihuitong.clinic')),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coverage', to='chihuitong.clinicagreement')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicCooperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('kind', models.CharField(choices=[('single', '单店'), ('chain', '连锁')], max_length=16)),
                ('status', models.CharField(default='active', max_length=16)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chihuitong.membership')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='clinic_cooperation', to='chihuitong.organization')),
            ],
        ),
        migrations.AddField(
            model_name='clinicagreement',
            name='cooperation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreements', to='chihuitong.cliniccooperation'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='cooperation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clinics', to='chihuitong.cliniccooperation'),
        ),
        migrations.AddField(
            model_name='clinicbill',
            name='cooperation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='chihuitong.cliniccooperation'),
        ),
        migrations.AddField(
            model_name='redemption',
            name='cooperation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='chihuitong.cliniccooperation'),
        ),
        migrations.AddConstraint(
            model_name='clinicbill',
            constraint=models.UniqueConstraint(fields=('cooperation', 'issued_on'), name='cooperation_bill_issue_date'),
        ),
        migrations.AddConstraint(
            model_name='clinicbill',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('clinic__isnull', False), ('cooperation__isnull', True)), models.Q(('clinic__isnull', True), ('cooperation__isnull', False)), _connector='OR'), name='bill_one_debtor'),
        ),
        migrations.AddField(
            model_name='instantredemptionorder',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chihuitong.clinicagreement'),
        ),
        migrations.AddField(
            model_name='instantredemptionorder',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instant_orders', to='chihuitong.appointment'),
        ),
        migrations.AddField(
            model_name='instantredemptionorder',
            name='cooperation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chihuitong.cliniccooperation'),
        ),
        migrations.AddField(
            model_name='instantredemptionorder',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chihuitong.membership'),
        ),
        migrations.AddField(
            model_name='instantredemptionorder',
            name='redemption',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instant_order', to='chihuitong.redemption'),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='instant_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_attempts', to='chihuitong.instantredemptionorder'),
        ),
        migrations.AddField(
            model_name='receiptledger',
            name='instant_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='chihuitong.instantredemptionorder'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('bill__isnull', False), ('instant_order__isnull', True)), models.Q(('bill__isnull', True), ('instant_order__isnull', False)), _connector='OR'), name='payment_one_target'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['creating', 'pending', 'unknown'])), fields=('instant_order',), name='one_unresolved_instant_payment'),
        ),
        migrations.AddConstraint(
            model_name='agreementclinic',
            constraint=models.UniqueConstraint(fields=('agreement', 'clinic'), name='agreement_clinic_once'),
        ),
        migrations.AddConstraint(
            model_name='cliniccooperation',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['single', 'chain'])), name='cooperation_kind'),
        ),
        migrations.AddConstraint(
            model_name='clinicagreement',
            constraint=models.UniqueConstraint(fields=('cooperation', 'revision'), name='agreement_revision'),
        ),
        migrations.AddConstraint(
            model_name='clinicagreement',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('cooperation',), name='one_pending_agreement'),
        ),
        migrations.AddConstraint(
            model_name='clinicagreement',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='agreement_dates'),
        ),
        migrations.AddConstraint(
            model_name='clinicagreement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('payment_mode', 'instant'), ('settlement_cycle', '')), models.Q(('payment_mode', 'postpaid'), ('settlement_cycle__in', ['weekly', 'monthly'])), _connector='OR'), name='agreement_payment_cycle'),
        ),
        migrations.AddConstraint(
            model_name='instantredemptionorder',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'paid', 'completed'])), fields=('appointment',), name='one_active_instant_order'),
        ),
        migrations.AddConstraint(
            model_name='instantredemptionorder',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'paid', 'completed', 'closed'])), name='instant_order_state'),
        ),
    ]
