# Generated by Django 5.2.17 on 2026-09-16 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chihuitong', '0017_instantredemptionorder_redemption_payment_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='contract_policy',
            field=models.CharField(default='legacy', max_length=16),
        ),
        migrations.AddField(
            model_name='clinicagreement',
            name='onboarding_change',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='onboarding_agreement', to='chihuitong.clinicprofilechange'),
        ),
        migrations.AddField(
            model_name='cliniccooperation',
            name='credit_code',
            field=models.CharField(max_length=18, null=True, unique=True),
        ),
    ]
