# Generated by Django 5.2.17 on 2026-09-16 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chihuitong', '0018_clinic_contract_policy_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='instantredemptionorder',
            name='one_active_instant_order',
        ),
        migrations.AddConstraint(
            model_name='instantredemptionorder',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'completed'])), fields=('appointment',), name='one_active_instant_order'),
        ),
    ]
