# Generated by Django 5.2.17 on 2026-09-16 05:38

import chihuitong.crypto
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chihuitong', '0019_remove_instantredemptionorder_one_active_instant_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractPreparation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('kind', models.CharField(choices=[('single', '单店'), ('chain', '连锁')], max_length=16)),
                ('number', models.CharField(max_length=80, unique=True)),
                ('payload', chihuitong.crypto.EncryptedJSONField(default=dict)),
                ('status', models.CharField(default='draft', max_length=16)),
                ('generation', models.PositiveIntegerField(default=0)),
                ('signed_ids', models.JSONField(default=list)),
                ('signed_generation', models.PositiveIntegerField(default=0)),
                ('agreement', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='chihuitong.clinicagreement')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chihuitong.membership')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('kind', models.CharField(choices=[('single', '单店'), ('chain', '连锁')], max_length=16)),
                ('title', models.CharField(max_length=160)),
                ('body', chihuitong.crypto.EncryptedTextField()),
                ('platform_name', models.CharField(max_length=160)),
                ('platform_credit_code', models.CharField(max_length=18)),
                ('status', models.CharField(default='active', max_length=16)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chihuitong.membership')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContractPrint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('revision', models.PositiveIntegerField()),
                ('snapshot', chihuitong.crypto.EncryptedJSONField()),
                ('fingerprint', models.CharField(max_length=64)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='chihuitong.fileasset')),
                ('preparation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prints', to='chihuitong.contractpreparation')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chihuitong.contracttemplate')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('preparation', 'revision'), name='contract_print_revision')],
            },
        ),
    ]
